"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es" | "fr" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    destinations: "Destinations",
    hotels: "Hotels",
    packages: "Packages",
    contact: "Contact",
    bookNow: "Book Now",
    searchPlaceholder: "Where do you want to go?",
    heroTitle: "Premium Red Velvet Travel",
    heroSubtitle: "Experience luxury like never before with our curated travel guides.",
    viewDetails: "View Details",
    exploreMore: "Explore More",
    contactAgent: "Contact Agent",
    login: "Login",
    signup: "Sign Up",
    profile: "Profile",
    logout: "Logout",
    featuredDestinations: "Featured Destinations",
    popularCategories: "Popular Categories",
    luxuryStays: "Luxury Stays",
    luxuryStaysDesc: "Curated collection of the world's most prestigious hotels and resorts.",
    curatedTourPackages: "Curated Tour Packages",
    curatedTourPackagesDesc: "Hand-crafted itineraries that combine the best of luxury, adventure, and culture.",
    exclusiveOffers: "Exclusive Offers",
    bookStay: "Book Stay",
    perNight: "per night",
    recommended: "Recommended",
    allInclusive: "All-inclusive",
    speakWithSpecialist: "Speak with a Specialist",
    speakWithSpecialistDesc: "Our luxury travel agents are ready to craft your perfect escape.",
    emailUs: "Email Us",
    callAnytime: "Call Anytime",
    fullName: "Full Name",
    emailAddress: "Email Address",
    yourInquiry: "Your Inquiry",
    inquiryPlaceholder: "Tell us about your dream destination...",
    sendInquiry: "Send Inquiry",
    sending: "Sending...",
    messageReceived: "Message Received",
    messageReceivedDesc: "One of our specialists will contact you shortly.",
    sendAnotherMessage: "Send Another Message",
    confirmBooking: "Confirm Your Booking",
    travelDates: "Travel Dates",
    numberOfTravelers: "Number of Travelers",
    paymentDetails: "Payment Details",
    cardholderName: "Cardholder Name",
    cardNumber: "Card Number",
    processing: "Processing...",
    completeBooking: "Complete Booking",
    baseFare: "Base Fare",
    taxesFees: "Taxes & Fees",
    total: "Total",
    secureCheckout: "Secure Checkout",
    welcome: "Welcome",
    accountSettings: "Account Settings",
    memberBenefits: "Member Benefits",
    premiumStatus: "Premium Status",
    exclusiveOffersAvailable: "Exclusive offers available",
    travelCreditAvailable: "Travel credit available",
    planNextTrip: "Plan your next trip",
    planNextTripDesc: "Explore our newly added destinations for winter 2024.",
    myBookings: "My Bookings",
    newBooking: "New Booking",
    viewDetailsBtn: "View Details",
    noBookingsYet: "You haven't booked any trips yet.",
    bookFirstTrip: "Book Your First Trip",
    aboutJourney: "About this journey",
    journeyHighlights: "Journey Highlights",
    whatsIncluded: "What's Included",
    premiumPackage: "Premium Package",
    selectDate: "Select Date",
    travelers: "Travelers",
    basePrice: "Base Price",
    serviceFee: "Service Fee",
    bookTripNow: "Book Your Trip Now",
    freeCancellation: "Free cancellation until 48 hours before the trip.",
    backToDestinations: "Back to Destinations",
    welcomeBack: "Welcome Back",
    enterCredentials: "Enter your credentials to access your luxury travels",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    createAccount: "Create Account",
    joinUs: "Join Orchids Travel for exclusive luxury travel experiences",
    creatingAccount: "Creating Account...",
    alreadyHaveAccount: "Already have an account?",
    flights: "Flights",
    flightsDesc: "Best deals on international and domestic flights.",
    tours: "Tours",
    toursDesc: "All-inclusive vacation deals for families.",
    readyForAdventure: "Ready for your next adventure?",
    readyForAdventureDesc: "Join thousands of travelers who have found their dream vacation with Orchids Travel. Get exclusive access to premium deals and personalized itineraries.",
    exploreFooter: "Explore",
    contactFooter: "Contact",
    addDates: "Add dates",
    search: "Search",
    noDestinationsFound: "No destinations found",
    noDestinationsFoundDesc: "Try adjusting your search or filters to find what you're looking for.",
    clearAllFilters: "Clear All Filters",
    startingFrom: "Starting from",
    all: "All",
    romantic: "Romantic",
    adventure: "Adventure",
    cultural: "Cultural",
    tropical: "Tropical",
    luxury: "Luxury",
  },
  es: {
    home: "Inicio",
    destinations: "Destinos",
    hotels: "Hoteles",
    packages: "Paquetes",
    contact: "Contacto",
    bookNow: "Reservar Ahora",
    searchPlaceholder: "¿A dónde quieres ir?",
    heroTitle: "Viajes Premium Terciopelo Rojo",
    heroSubtitle: "Experimente el lujo como nunca antes con nuestras guías de viaje seleccionadas.",
    viewDetails: "Ver Detalles",
    exploreMore: "Explorar Más",
    contactAgent: "Contactar Agente",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    profile: "Perfil",
    logout: "Cerrar Sesión",
    featuredDestinations: "Destinos Destacados",
    popularCategories: "Categorías Populares",
    luxuryStays: "Estancias de Lujo",
    luxuryStaysDesc: "Colección curada de los hoteles y resorts más prestigiosos del mundo.",
    curatedTourPackages: "Paquetes de Tours Curados",
    curatedTourPackagesDesc: "Itinerarios hechos a mano que combinan lo mejor del lujo, la aventura y la cultura.",
    exclusiveOffers: "Ofertas Exclusivas",
    bookStay: "Reservar Estancia",
    perNight: "por noche",
    recommended: "Recomendado",
    allInclusive: "Todo Incluido",
    speakWithSpecialist: "Habla con un Especialista",
    speakWithSpecialistDesc: "Nuestros agentes de viajes de lujo están listos para crear tu escapada perfecta.",
    emailUs: "Envíanos un Email",
    callAnytime: "Llámanos",
    fullName: "Nombre Completo",
    emailAddress: "Correo Electrónico",
    yourInquiry: "Tu Consulta",
    inquiryPlaceholder: "Cuéntanos sobre tu destino soñado...",
    sendInquiry: "Enviar Consulta",
    sending: "Enviando...",
    messageReceived: "Mensaje Recibido",
    messageReceivedDesc: "Uno de nuestros especialistas te contactará pronto.",
    sendAnotherMessage: "Enviar Otro Mensaje",
    confirmBooking: "Confirma tu Reserva",
    travelDates: "Fechas de Viaje",
    numberOfTravelers: "Número de Viajeros",
    paymentDetails: "Detalles de Pago",
    cardholderName: "Nombre del Titular",
    cardNumber: "Número de Tarjeta",
    processing: "Procesando...",
    completeBooking: "Completar Reserva",
    baseFare: "Tarifa Base",
    taxesFees: "Impuestos y Tasas",
    total: "Total",
    secureCheckout: "Pago Seguro",
    welcome: "Bienvenido",
    accountSettings: "Configuración de Cuenta",
    memberBenefits: "Beneficios de Miembro",
    premiumStatus: "Estado Premium",
    exclusiveOffersAvailable: "Ofertas exclusivas disponibles",
    travelCreditAvailable: "Crédito de viaje disponible",
    planNextTrip: "Planifica tu próximo viaje",
    planNextTripDesc: "Explora nuestros destinos recién añadidos para invierno 2024.",
    myBookings: "Mis Reservas",
    newBooking: "Nueva Reserva",
    viewDetailsBtn: "Ver Detalles",
    noBookingsYet: "Aún no has reservado ningún viaje.",
    bookFirstTrip: "Reserva tu Primer Viaje",
    aboutJourney: "Sobre este viaje",
    journeyHighlights: "Destacados del Viaje",
    whatsIncluded: "Qué está Incluido",
    premiumPackage: "Paquete Premium",
    selectDate: "Seleccionar Fecha",
    travelers: "Viajeros",
    basePrice: "Precio Base",
    serviceFee: "Tarifa de Servicio",
    bookTripNow: "Reserva tu Viaje Ahora",
    freeCancellation: "Cancelación gratuita hasta 48 horas antes del viaje.",
    backToDestinations: "Volver a Destinos",
    welcomeBack: "Bienvenido de Nuevo",
    enterCredentials: "Ingresa tus credenciales para acceder a tus viajes de lujo",
    email: "Correo",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    signIn: "Iniciar Sesión",
    signingIn: "Iniciando sesión...",
    noAccount: "¿No tienes cuenta?",
    createAccount: "Crear Cuenta",
    joinUs: "Únete a Orchids Travel para experiencias de viaje de lujo exclusivas",
    creatingAccount: "Creando Cuenta...",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    flights: "Vuelos",
    flightsDesc: "Las mejores ofertas en vuelos internacionales y domésticos.",
    tours: "Tours",
    toursDesc: "Paquetes de vacaciones todo incluido para familias.",
    readyForAdventure: "¿Listo para tu próxima aventura?",
    readyForAdventureDesc: "Únete a miles de viajeros que han encontrado sus vacaciones soñadas con Orchids Travel. Obtén acceso exclusivo a ofertas premium e itinerarios personalizados.",
    exploreFooter: "Explorar",
    contactFooter: "Contacto",
    addDates: "Agregar fechas",
    search: "Buscar",
    noDestinationsFound: "No se encontraron destinos",
    noDestinationsFoundDesc: "Intenta ajustar tu búsqueda o filtros para encontrar lo que buscas.",
    clearAllFilters: "Limpiar Todos los Filtros",
    startingFrom: "Desde",
    all: "Todos",
    romantic: "Romántico",
    adventure: "Aventura",
    cultural: "Cultural",
    tropical: "Tropical",
    luxury: "Lujo",
  },
  fr: {
    home: "Accueil",
    destinations: "Destinations",
    hotels: "Hôtels",
    packages: "Forfaits",
    contact: "Contact",
    bookNow: "Réserver",
    searchPlaceholder: "Où voulez-vous aller ?",
    heroTitle: "Voyage Premium Velours Rouge",
    heroSubtitle: "Découvrez le luxe comme jamais auparavant avec nos guides de voyage sélectionnés.",
    viewDetails: "Voir les Détails",
    exploreMore: "Explorer Plus",
    contactAgent: "Contacter l'Agent",
    login: "Connexion",
    signup: "S'inscrire",
    profile: "Profil",
    logout: "Déconnexion",
    featuredDestinations: "Destinations Vedettes",
    popularCategories: "Catégories Populaires",
    luxuryStays: "Séjours de Luxe",
    luxuryStaysDesc: "Collection soigneusement sélectionnée des hôtels et resorts les plus prestigieux du monde.",
    curatedTourPackages: "Forfaits Tours Sélectionnés",
    curatedTourPackagesDesc: "Itinéraires faits à la main combinant le meilleur du luxe, de l'aventure et de la culture.",
    exclusiveOffers: "Offres Exclusives",
    bookStay: "Réserver le Séjour",
    perNight: "par nuit",
    recommended: "Recommandé",
    allInclusive: "Tout Compris",
    speakWithSpecialist: "Parlez à un Spécialiste",
    speakWithSpecialistDesc: "Nos agents de voyage de luxe sont prêts à créer votre évasion parfaite.",
    emailUs: "Envoyez-nous un Email",
    callAnytime: "Appelez-nous",
    fullName: "Nom Complet",
    emailAddress: "Adresse Email",
    yourInquiry: "Votre Demande",
    inquiryPlaceholder: "Parlez-nous de votre destination de rêve...",
    sendInquiry: "Envoyer la Demande",
    sending: "Envoi en cours...",
    messageReceived: "Message Reçu",
    messageReceivedDesc: "Un de nos spécialistes vous contactera bientôt.",
    sendAnotherMessage: "Envoyer un Autre Message",
    confirmBooking: "Confirmez Votre Réservation",
    travelDates: "Dates de Voyage",
    numberOfTravelers: "Nombre de Voyageurs",
    paymentDetails: "Détails de Paiement",
    cardholderName: "Nom du Titulaire",
    cardNumber: "Numéro de Carte",
    processing: "Traitement...",
    completeBooking: "Finaliser la Réservation",
    baseFare: "Tarif de Base",
    taxesFees: "Taxes et Frais",
    total: "Total",
    secureCheckout: "Paiement Sécurisé",
    welcome: "Bienvenue",
    accountSettings: "Paramètres du Compte",
    memberBenefits: "Avantages Membre",
    premiumStatus: "Statut Premium",
    exclusiveOffersAvailable: "Offres exclusives disponibles",
    travelCreditAvailable: "Crédit voyage disponible",
    planNextTrip: "Planifiez votre prochain voyage",
    planNextTripDesc: "Explorez nos destinations nouvellement ajoutées pour l'hiver 2024.",
    myBookings: "Mes Réservations",
    newBooking: "Nouvelle Réservation",
    viewDetailsBtn: "Voir les Détails",
    noBookingsYet: "Vous n'avez pas encore réservé de voyage.",
    bookFirstTrip: "Réservez Votre Premier Voyage",
    aboutJourney: "À propos de ce voyage",
    journeyHighlights: "Points Forts du Voyage",
    whatsIncluded: "Ce qui est Inclus",
    premiumPackage: "Forfait Premium",
    selectDate: "Sélectionner la Date",
    travelers: "Voyageurs",
    basePrice: "Prix de Base",
    serviceFee: "Frais de Service",
    bookTripNow: "Réservez Votre Voyage",
    freeCancellation: "Annulation gratuite jusqu'à 48 heures avant le voyage.",
    backToDestinations: "Retour aux Destinations",
    welcomeBack: "Bon Retour",
    enterCredentials: "Entrez vos identifiants pour accéder à vos voyages de luxe",
    email: "Email",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    signIn: "Se Connecter",
    signingIn: "Connexion...",
    noAccount: "Pas de compte ?",
    createAccount: "Créer un Compte",
    joinUs: "Rejoignez Orchids Travel pour des expériences de voyage de luxe exclusives",
    creatingAccount: "Création du compte...",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    flights: "Vols",
    flightsDesc: "Les meilleures offres sur les vols internationaux et domestiques.",
    tours: "Tours",
    toursDesc: "Forfaits vacances tout compris pour les familles.",
    readyForAdventure: "Prêt pour votre prochaine aventure ?",
    readyForAdventureDesc: "Rejoignez des milliers de voyageurs qui ont trouvé leurs vacances de rêve avec Orchids Travel. Accédez exclusivement à des offres premium et des itinéraires personnalisés.",
    exploreFooter: "Explorer",
    contactFooter: "Contact",
    addDates: "Ajouter des dates",
    search: "Rechercher",
    noDestinationsFound: "Aucune destination trouvée",
    noDestinationsFoundDesc: "Essayez d'ajuster votre recherche ou vos filtres.",
    clearAllFilters: "Effacer Tous les Filtres",
    startingFrom: "À partir de",
    all: "Tous",
    romantic: "Romantique",
    adventure: "Aventure",
    cultural: "Culturel",
    tropical: "Tropical",
    luxury: "Luxe",
  },
  de: {
    home: "Startseite",
    destinations: "Reiseziele",
    hotels: "Hotels",
    packages: "Pakete",
    contact: "Kontakt",
    bookNow: "Jetzt Buchen",
    searchPlaceholder: "Wohin möchten Sie gehen?",
    heroTitle: "Premium Roter Samt Reisen",
    heroSubtitle: "Erleben Sie Luxus wie nie zuvor mit unseren kuratierten Reiseführern.",
    viewDetails: "Details Anzeigen",
    exploreMore: "Mehr Erkunden",
    contactAgent: "Agent Kontaktieren",
    login: "Anmelden",
    signup: "Registrieren",
    profile: "Profil",
    logout: "Abmelden",
    featuredDestinations: "Beliebte Reiseziele",
    popularCategories: "Beliebte Kategorien",
    luxuryStays: "Luxusaufenthalte",
    luxuryStaysDesc: "Kuratierte Sammlung der prestigeträchtigsten Hotels und Resorts der Welt.",
    curatedTourPackages: "Kuratierte Tourpakete",
    curatedTourPackagesDesc: "Handgefertigte Reiserouten, die das Beste aus Luxus, Abenteuer und Kultur vereinen.",
    exclusiveOffers: "Exklusive Angebote",
    bookStay: "Aufenthalt Buchen",
    perNight: "pro Nacht",
    recommended: "Empfohlen",
    allInclusive: "All-Inclusive",
    speakWithSpecialist: "Sprechen Sie mit einem Spezialisten",
    speakWithSpecialistDesc: "Unsere Luxus-Reiseagenten sind bereit, Ihren perfekten Urlaub zu gestalten.",
    emailUs: "E-Mail",
    callAnytime: "Anrufen",
    fullName: "Vollständiger Name",
    emailAddress: "E-Mail-Adresse",
    yourInquiry: "Ihre Anfrage",
    inquiryPlaceholder: "Erzählen Sie uns von Ihrem Traumziel...",
    sendInquiry: "Anfrage Senden",
    sending: "Senden...",
    messageReceived: "Nachricht Erhalten",
    messageReceivedDesc: "Einer unserer Spezialisten wird Sie in Kürze kontaktieren.",
    sendAnotherMessage: "Weitere Nachricht Senden",
    confirmBooking: "Bestätigen Sie Ihre Buchung",
    travelDates: "Reisedaten",
    numberOfTravelers: "Anzahl der Reisenden",
    paymentDetails: "Zahlungsdetails",
    cardholderName: "Name des Karteninhabers",
    cardNumber: "Kartennummer",
    processing: "Verarbeitung...",
    completeBooking: "Buchung Abschließen",
    baseFare: "Grundpreis",
    taxesFees: "Steuern & Gebühren",
    total: "Gesamt",
    secureCheckout: "Sichere Zahlung",
    welcome: "Willkommen",
    accountSettings: "Kontoeinstellungen",
    memberBenefits: "Mitgliedsvorteile",
    premiumStatus: "Premium-Status",
    exclusiveOffersAvailable: "Exklusive Angebote verfügbar",
    travelCreditAvailable: "Reiseguthaben verfügbar",
    planNextTrip: "Planen Sie Ihre nächste Reise",
    planNextTripDesc: "Entdecken Sie unsere neu hinzugefügten Ziele für Winter 2024.",
    myBookings: "Meine Buchungen",
    newBooking: "Neue Buchung",
    viewDetailsBtn: "Details Anzeigen",
    noBookingsYet: "Sie haben noch keine Reisen gebucht.",
    bookFirstTrip: "Buchen Sie Ihre Erste Reise",
    aboutJourney: "Über diese Reise",
    journeyHighlights: "Reise-Highlights",
    whatsIncluded: "Was enthalten ist",
    premiumPackage: "Premium-Paket",
    selectDate: "Datum Auswählen",
    travelers: "Reisende",
    basePrice: "Grundpreis",
    serviceFee: "Servicegebühr",
    bookTripNow: "Jetzt Reise Buchen",
    freeCancellation: "Kostenlose Stornierung bis 48 Stunden vor der Reise.",
    backToDestinations: "Zurück zu Reisezielen",
    welcomeBack: "Willkommen Zurück",
    enterCredentials: "Geben Sie Ihre Anmeldedaten ein, um auf Ihre Luxusreisen zuzugreifen",
    email: "E-Mail",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",
    signIn: "Anmelden",
    signingIn: "Anmeldung...",
    noAccount: "Kein Konto?",
    createAccount: "Konto Erstellen",
    joinUs: "Treten Sie Orchids Travel für exklusive Luxusreiseerlebnisse bei",
    creatingAccount: "Konto wird erstellt...",
    alreadyHaveAccount: "Haben Sie bereits ein Konto?",
    flights: "Flüge",
    flightsDesc: "Beste Angebote für internationale und inländische Flüge.",
    tours: "Touren",
    toursDesc: "All-Inclusive-Urlaubspakete für Familien.",
    readyForAdventure: "Bereit für Ihr nächstes Abenteuer?",
    readyForAdventureDesc: "Schließen Sie sich Tausenden von Reisenden an, die ihren Traumurlaub mit Orchids Travel gefunden haben. Erhalten Sie exklusiven Zugang zu Premium-Angeboten und personalisierten Reiserouten.",
    exploreFooter: "Erkunden",
    contactFooter: "Kontakt",
    addDates: "Daten hinzufügen",
    search: "Suchen",
    noDestinationsFound: "Keine Reiseziele gefunden",
    noDestinationsFoundDesc: "Versuchen Sie, Ihre Suche oder Filter anzupassen.",
    clearAllFilters: "Alle Filter Löschen",
    startingFrom: "Ab",
    all: "Alle",
    romantic: "Romantisch",
    adventure: "Abenteuer",
    cultural: "Kulturell",
    tropical: "Tropisch",
    luxury: "Luxus",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
