"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es" | "fr" | "de" | "hi" | "ta" | "te" | "kn" | "ml" | "zh" | "ja" | "vi" | "ru";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    destinations: "Destinations",
    hotels: "Hotels",
    packages: "Packages",
    contact: "Contact",
    bookNow: "Book Now",
    searchPlaceholder: "Where do you want to go?",
    heroTitle: "Premium Red Velvet Travel",
    heroSubtitle: "Experience luxury like never before with our curated travel guides.",
    viewDetails: "View Details",
    exploreMore: "Explore More",
    contactAgent: "Contact Agent",
    login: "Login",
    signup: "Sign Up",
    profile: "Profile",
    logout: "Logout",
    featuredDestinations: "Featured Destinations",
    popularCategories: "Popular Categories",
    luxuryStays: "Luxury Stays",
      luxuryStaysDesc: "Curated collection of India's most prestigious hotels and resorts.",
      curatedTourPackages: "Curated Tour Packages",
      curatedTourPackagesDesc: "Hand-crafted itineraries that combine the best of luxury, adventure, and culture across India.",
      exclusiveOffers: "Exclusive Offers",
      bookStay: "Book Stay",
      perNight: "per night",
      recommended: "Recommended",
      allInclusive: "All-inclusive",
      experienceIndia: "Experience India",
      experiencePackages: "Experience Packages",
      experiencePackagesDesc: "Curated travel experiences for every type of traveler in India",
      exploreIndia: "Explore India",
      popularDestinations: "Popular Destinations",
      popularDestinationsDesc: "Discover India's most breathtaking destinations",
      viewAll: "View All",
      footerDesc: "India's first premium travel platform designed for the modern adventurer. Luxury, simplified.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    allRightsReserved: "All rights reserved.",
    heritageAndCulture: "Heritage & Culture",
    heritageAndCultureDesc: "Ancient temples & monuments",
    adventureAndThrills: "Adventure & Thrills",
    adventureAndThrillsDesc: "Trekking & extreme sports",
    wildlifeSafari: "Wildlife Safari",
    wildlifeSafariDesc: "National parks & reserves",
    beachAndRelaxation: "Beach & Relaxation",
    beachAndRelaxationDesc: "Coastal getaways",
    spiritualJourneys: "Spiritual Journeys",
    spiritualJourneysDesc: "Pilgrimage & wellness",
    foodAndCulinary: "Food & Culinary",
    foodAndCulinaryDesc: "Local cuisine experiences",
    wifi: "Wifi",
    breakfast: "Breakfast",
    pool: "Pool",
    dining: "Dining",
    speakWithSpecialist: "Speak with a Specialist",
    speakWithSpecialistDesc: "Our luxury travel agents are ready to craft your perfect escape.",
    emailUs: "Email Us",
    callAnytime: "Call Anytime",
    fullName: "Full Name",
    emailAddress: "Email Address",
    yourInquiry: "Your Inquiry",
    inquiryPlaceholder: "Tell us about your dream destination...",
    sendInquiry: "Send Inquiry",
    sending: "Sending...",
    messageReceived: "Message Received",
    messageReceivedDesc: "One of our specialists will contact you shortly.",
    sendAnotherMessage: "Send Another Message",
    confirmBooking: "Confirm Your Booking",
    travelDates: "Travel Dates",
    numberOfTravelers: "Number of Travelers",
    paymentDetails: "Payment Details",
    cardholderName: "Cardholder Name",
    cardNumber: "Card Number",
    processing: "Processing...",
    completeBooking: "Complete Booking",
    baseFare: "Base Fare",
    taxesFees: "Taxes & Fees",
    total: "Total",
    secureCheckout: "Secure Checkout",
    welcome: "Welcome",
    accountSettings: "Account Settings",
    memberBenefits: "Member Benefits",
    premiumStatus: "Premium Status",
    exclusiveOffersAvailable: "Exclusive offers available",
    travelCreditAvailable: "Travel credit available",
    planNextTrip: "Plan your next trip",
    planNextTripDesc: "Explore our newly added destinations for winter 2024.",
    myBookings: "My Bookings",
    newBooking: "New Booking",
    viewDetailsBtn: "View Details",
    noBookingsYet: "You haven't booked any trips yet.",
    bookFirstTrip: "Book Your First Trip",
    aboutJourney: "About this journey",
    journeyHighlights: "Journey Highlights",
    whatsIncluded: "What's Included",
    premiumPackage: "Premium Package",
    selectDate: "Select Date",
    travelers: "Travelers",
    basePrice: "Base Price",
    serviceFee: "Service Fee",
    bookTripNow: "Book Your Trip Now",
    freeCancellation: "Free cancellation until 48 hours before the trip.",
    backToDestinations: "Back to Destinations",
    welcomeBack: "Welcome Back",
    enterCredentials: "Enter your credentials to access your luxury travels",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign In",
    signingIn: "Signing in...",
    noAccount: "Don't have an account?",
    createAccount: "Create Account",
    joinUs: "Join Orchids Travel for exclusive luxury travel experiences",
    creatingAccount: "Creating Account...",
    alreadyHaveAccount: "Already have an account?",
    flights: "Flights",
    flightsDesc: "Best deals on international and domestic flights.",
    tours: "Tours",
    toursDesc: "All-inclusive vacation deals for families.",
    readyForAdventure: "Ready for your next adventure?",
    readyForAdventureDesc: "Join thousands of travelers who have found their dream vacation with Orchids Travel. Get exclusive access to premium deals and personalized itineraries.",
    exploreFooter: "Explore",
    contactFooter: "Contact",
    addDates: "Add dates",
    search: "Search",
    noDestinationsFound: "No destinations found",
    noDestinationsFoundDesc: "Try adjusting your search or filters to find what you're looking for.",
    clearAllFilters: "Clear All Filters",
    startingFrom: "Starting from",
    all: "All",
    romantic: "Romantic",
    adventure: "Adventure",
    cultural: "Cultural",
    tropical: "Tropical",
    luxury: "Luxury",
    viewAllPackages: "View All Packages",
    viewAllHotels: "View All Hotels",
    guestReviews: "Guest Reviews",
    reviewsCount: "reviews",
    noReviewsYet: "No reviews yet. Be the first to share your experience!",
    writeAReview: "Write a Review",
    loginToReview: "Please log in to share your experience with other travelers.",
    reviewPlaceholder: "Share your experience...",
    submitting: "Submitting...",
    submitReview: "Submit Review",
    backToHotels: "Back to Hotels",
    night: "night",
    aboutTheHotel: "About the Hotel",
    featuredAmenities: "Featured Amenities",
    allAmenities: "All Amenities",
    bestPriceGuaranteed: "Best Price Guaranteed",
    bookYourStay: "Book Your Stay",
    checkAvailability: "Check Availability",
    freeCancellationHotel: "Free cancellation until 48h before check-in",
    backToPackages: "Back to Packages",
    packageDescription: "Package Description",
    bestValue: "Best Value",
    perPackage: "total",
    selectDepartureDate: "Select Departure Date",
    bookPackageNow: "Book This Package",
    customizeItinerary: "Customize Itinerary",
    priceIncludesTax: "Price includes all taxes and fees",
    insuranceIncluded: "Travel Insurance Included",
    destinationNotFound: "Destination Not Found",
    destinationNotFoundDesc: "The destination you are looking for does not exist.",
    errorInvalidCredentials: "Invalid email or password.",
    errorEmailNotConfirmed: "Please confirm your email address.",
    errorRateLimit: "Too many attempts. Please try again later.",
    errorUnexpected: "An unexpected error occurred.",
    checkEmailConfirm: "Please check your email to confirm your account.",
  },
  es: {
    home: "Inicio",
    destinations: "Destinos",
    hotels: "Hoteles",
    packages: "Paquetes",
    contact: "Contacto",
    bookNow: "Reservar Ahora",
    searchPlaceholder: "¿A dónde quieres ir?",
    heroTitle: "Viajes Premium Terciopelo Rojo",
    heroSubtitle: "Experimente el lujo como nunca antes con nuestras guías de viaje seleccionadas.",
    viewDetails: "Ver Detalles",
    exploreMore: "Explorar Más",
    contactAgent: "Contactar Agente",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    profile: "Perfil",
    logout: "Cerrar Sesión",
    featuredDestinations: "Destinos Destacados",
    popularCategories: "Categorías Populares",
    luxuryStays: "Estancias de Lujo",
    luxuryStaysDesc: "Colección curada de los hoteles y resorts más prestigiosos del mundo.",
    curatedTourPackages: "Paquetes de Tours Curados",
    curatedTourPackagesDesc: "Itinerarios hechos a mano que combinan lo mejor del lujo, la aventura y la cultura.",
    exclusiveOffers: "Ofertas Exclusivas",
    bookStay: "Reservar Estancia",
    perNight: "por noche",
    recommended: "Recomendado",
    allInclusive: "Todo Incluido",
    experienceIndia: "Experiencia India",
    experiencePackages: "Paquetes de Experiencia",
    experiencePackagesDesc: "Experiencias de viaje seleccionadas para cada tipo de viajero",
    exploreWorld: "Explorar el Mundo",
    popularDestinations: "Destinos Populares",
    popularDestinationsDesc: "Descubre los destinos más impresionantes del mundo",
    viewAll: "Ver Todo",
    footerDesc: "La primera plataforma de viajes premium del mundo diseñada para el aventurero moderno. Lujo, simplificado.",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    allRightsReserved: "Todos los derechos reservados.",
    heritageAndCulture: "Patrimonio y Cultura",
    heritageAndCultureDesc: "Templos y monumentos antiguos",
    adventureAndThrills: "Aventura y Emociones",
    adventureAndThrillsDesc: "Senderismo y deportes extremos",
    wildlifeSafari: "Safari de Vida Silvestre",
    wildlifeSafariDesc: "Parques nacionales y reservas",
    beachAndRelaxation: "Playa y Relax",
    beachAndRelaxationDesc: "Escapadas costeras",
    spiritualJourneys: "Viajes Espirituales",
    spiritualJourneysDesc: "Peregrinación y bienestar",
    foodAndCulinary: "Gastronomía y Culinaria",
    foodAndCulinaryDesc: "Experiencias de cocina local",
    wifi: "Wifi",
    breakfast: "Desayuno",
    pool: "Piscina",
    dining: "Restaurante",
    speakWithSpecialist: "Habla con un Especialista",
    speakWithSpecialistDesc: "Nuestros agentes de viajes de lujo están listos para crear tu escapada perfecta.",
    emailUs: "Envíanos un Email",
    callAnytime: "Llámanos",
    fullName: "Nombre Completo",
    emailAddress: "Correo Electrónico",
    yourInquiry: "Tu Consulta",
    inquiryPlaceholder: "Cuéntanos sobre tu destino soñado...",
    sendInquiry: "Enviar Consulta",
    sending: "Enviando...",
    messageReceived: "Mensaje Recibido",
    messageReceivedDesc: "Uno de nuestros especialistas te contactará pronto.",
    sendAnotherMessage: "Enviar Otro Mensaje",
    confirmBooking: "Confirma tu Reserva",
    travelDates: "Fechas de Viaje",
    numberOfTravelers: "Número de Viajeros",
    paymentDetails: "Detalles de Pago",
    cardholderName: "Nombre del Titular",
    cardNumber: "Número de Tarjeta",
    processing: "Procesando...",
    completeBooking: "Completar Reserva",
    baseFare: "Tarifa Base",
    taxesFees: "Impuestos y Tasas",
    total: "Total",
    secureCheckout: "Pago Seguro",
    welcome: "Bienvenido",
    accountSettings: "Configuración de Cuenta",
    memberBenefits: "Beneficios de Miembro",
    premiumStatus: "Estado Premium",
    exclusiveOffersAvailable: "Ofertas exclusivas disponibles",
    travelCreditAvailable: "Crédito de viaje disponible",
    planNextTrip: "Planifica tu próximo viaje",
    planNextTripDesc: "Explora nuestros destinos recién añadidos para invierno 2024.",
    myBookings: "Mis Reservas",
    newBooking: "Nueva Reserva",
    viewDetailsBtn: "Ver Detalles",
    noBookingsYet: "Aún no has reservado ningún viaje.",
    bookFirstTrip: "Reserva tu Primer Viaje",
    aboutJourney: "Sobre este viaje",
    journeyHighlights: "Destacados del Viaje",
    whatsIncluded: "Qué está Incluido",
    premiumPackage: "Paquete Premium",
    selectDate: "Seleccionar Fecha",
    travelers: "Viajeros",
    basePrice: "Precio Base",
    serviceFee: "Tarifa de Servicio",
    bookTripNow: "Reserva tu Viaje Ahora",
    freeCancellation: "Cancelación gratuita hasta 48 horas antes del viaje.",
    backToDestinations: "Volver a Destinos",
    welcomeBack: "Bienvenido de Nuevo",
    enterCredentials: "Ingresa tus credenciales para acceder a tus viajes de lujo",
    email: "Correo",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    signIn: "Iniciar Sesión",
    signingIn: "Iniciando sesión...",
    noAccount: "¿No tienes cuenta?",
    createAccount: "Crear Cuenta",
    joinUs: "Únete a Orchids Travel para experiencias de viaje de lujo exclusivas",
    creatingAccount: "Creando Cuenta...",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    flights: "Vuelos",
    flightsDesc: "Las mejores ofertas en vuelos internacionales y domésticos.",
    tours: "Tours",
    toursDesc: "Paquetes de vacaciones todo incluido para familias.",
    readyForAdventure: "¿Listo para tu próxima aventura?",
    readyForAdventureDesc: "Únete a miles de viajeros que han encontrado sus vacaciones soñadas con Orchids Travel. Obtén acceso exclusivo a ofertas premium e itinerarios personalizados.",
    exploreFooter: "Explorar",
    contactFooter: "Contacto",
    addDates: "Agregar fechas",
    search: "Buscar",
    noDestinationsFound: "No se encontraron destinos",
    noDestinationsFoundDesc: "Intenta ajustar tu búsqueda o filtros para encontrar lo que buscas.",
    clearAllFilters: "Limpiar Todos los Filtros",
    startingFrom: "Desde",
    all: "Todos",
    romantic: "Romántico",
    adventure: "Aventura",
    cultural: "Cultural",
    tropical: "Tropical",
    luxury: "Lujo",
    viewAllPackages: "Ver Todos los Paquetes",
    viewAllHotels: "Ver Todos los Hoteles",
    guestReviews: "Opiniones de Huéspedes",
    reviewsCount: "opiniones",
    noReviewsYet: "Aún no hay opiniones. ¡Sé el primero en compartir tu experiencia!",
    writeAReview: "Escribir una Opinión",
    loginToReview: "Inicia sesión para compartir tu experiencia.",
    reviewPlaceholder: "Comparte tu experiencia...",
    submitting: "Enviando...",
    submitReview: "Enviar Opinión",
    backToHotels: "Volver a Hoteles",
    night: "noche",
    aboutTheHotel: "Sobre el Hotel",
    featuredAmenities: "Servicios Destacados",
    allAmenities: "Todos los Servicios",
    bestPriceGuaranteed: "Mejor Precio Garantizado",
    bookYourStay: "Reservar Estancia",
    checkAvailability: "Ver Disponibilidad",
    freeCancellationHotel: "Cancelación gratuita hasta 48h antes del check-in",
    backToPackages: "Volver a Paquetes",
    packageDescription: "Descripción del Paquete",
    bestValue: "Mejor Valor",
    perPackage: "total",
    selectDepartureDate: "Seleccionar Fecha de Salida",
    bookPackageNow: "Reservar Este Paquete",
    customizeItinerary: "Personalizar Itinerario",
    priceIncludesTax: "El precio incluye todos los impuestos",
    insuranceIncluded: "Seguro de Viaje Incluido",
    destinationNotFound: "Destino No Encontrado",
    destinationNotFoundDesc: "El destino que buscas no existe.",
    errorInvalidCredentials: "Correo o contraseña inválidos.",
    errorEmailNotConfirmed: "Por favor confirme su correo electrónico.",
    errorRateLimit: "Demasiados intentos. Inténtelo más tarde.",
    errorUnexpected: "Ocurrió un error inesperado.",
    checkEmailConfirm: "Por favor, revise su correo electrónico para confirmar su cuenta.",
  },
  fr: {
    home: "Accueil",
    destinations: "Destinations",
    hotels: "Hôtels",
    packages: "Forfaits",
    contact: "Contact",
    bookNow: "Réserver",
    searchPlaceholder: "Où voulez-vous aller ?",
    heroTitle: "Voyage Premium Velours Rouge",
    heroSubtitle: "Découvrez le luxe comme jamais auparavant avec nos guides de voyage sélectionnés.",
    viewDetails: "Voir les Détails",
    exploreMore: "Explorer Plus",
    contactAgent: "Contacter l'Agent",
    login: "Connexion",
    signup: "S'inscrire",
    profile: "Profil",
    logout: "Déconnexion",
    featuredDestinations: "Destinations Vedettes",
    popularCategories: "Catégories Populaires",
    luxuryStays: "Séjours de Luxe",
    luxuryStaysDesc: "Collection soigneusement sélectionnée des hôtels et resorts les plus prestigieux du monde.",
    curatedTourPackages: "Forfaits Tours Sélectionnés",
    curatedTourPackagesDesc: "Itinéraires faits à la main combinant le meilleur du luxe, de l'aventure et de la culture.",
    exclusiveOffers: "Offres Exclusives",
    bookStay: "Réserver le Séjour",
    perNight: "par nuit",
    recommended: "Recommandé",
    allInclusive: "Tout Compris",
    experienceIndia: "Découvrir l'Inde",
    experiencePackages: "Forfaits Expérience",
    experiencePackagesDesc: "Expériences de voyage sélectionnées pour chaque type de voyageur",
    exploreWorld: "Explorer le Monde",
    popularDestinations: "Destinations Populaires",
    popularDestinationsDesc: "Découvrez les destinations les plus époustouflantes du monde",
    viewAll: "Voir Tout",
    footerDesc: "La première plateforme de voyage premium au monde conçue pour l'aventurier moderne. Le luxe, simplifié.",
    privacyPolicy: "Politique de Confidentialité",
    termsOfService: "Conditions d'Utilisation",
    allRightsReserved: "Tous droits réservés.",
    heritageAndCulture: "Patrimoine et Culture",
    heritageAndCultureDesc: "Temples et monuments anciens",
    adventureAndThrills: "Aventure et Sensations",
    adventureAndThrillsDesc: "Randonnée et sports extrêmes",
    wildlifeSafari: "Safari Animalier",
    wildlifeSafariDesc: "Parcs nationaux et réserves",
    beachAndRelaxation: "Plage et Détente",
    beachAndRelaxationDesc: "Escapades côtières",
    spiritualJourneys: "Voyages Spirituels",
    spiritualJourneysDesc: "Pèlerinage et bien-être",
    foodAndCulinary: "Gastronomie",
    foodAndCulinaryDesc: "Expériences culinaires locales",
    wifi: "Wifi",
    breakfast: "Petit-déjeuner",
    pool: "Piscine",
    dining: "Restaurant",
    speakWithSpecialist: "Parlez à un Spécialiste",
    speakWithSpecialistDesc: "Nos agents de voyage de luxe sont prêts à créer votre évasion parfaite.",
    emailUs: "Envoyez-nous un Email",
    callAnytime: "Appelez-nous",
    fullName: "Nom Complet",
    emailAddress: "Adresse Email",
    yourInquiry: "Votre Demande",
    inquiryPlaceholder: "Parlez-nous de votre destination de rêve...",
    sendInquiry: "Envoyer la Demande",
    sending: "Envoi en cours...",
    messageReceived: "Message Reçu",
    messageReceivedDesc: "Un de nos spécialistes vous contactera bientôt.",
    sendAnotherMessage: "Envoyer un Autre Message",
    confirmBooking: "Confirmez Votre Réservation",
    travelDates: "Dates de Voyage",
    numberOfTravelers: "Nombre de Voyageurs",
    paymentDetails: "Détails de Paiement",
    cardholderName: "Nom du Titulaire",
    cardNumber: "Numéro de Carte",
    processing: "Traitement...",
    completeBooking: "Finaliser la Réservation",
    baseFare: "Tarif de Base",
    taxesFees: "Taxes et Frais",
    total: "Total",
    secureCheckout: "Paiement Sécurisé",
    welcome: "Bienvenue",
    accountSettings: "Paramètres du Compte",
    memberBenefits: "Avantages Membre",
    premiumStatus: "Statut Premium",
    exclusiveOffersAvailable: "Offres exclusives disponibles",
    travelCreditAvailable: "Crédit voyage disponible",
    planNextTrip: "Planifiez votre prochain voyage",
    planNextTripDesc: "Explorez nos destinations nouvellement ajoutées pour l'hiver 2024.",
    myBookings: "Mes Réservations",
    newBooking: "Nouvelle Réservation",
    viewDetailsBtn: "Voir les Détails",
    noBookingsYet: "Vous n'avez pas encore réservé de voyage.",
    bookFirstTrip: "Réservez Votre Premier Voyage",
    aboutJourney: "À propos de ce voyage",
    journeyHighlights: "Points Forts du Voyage",
    whatsIncluded: "Ce qui est Inclus",
    premiumPackage: "Forfait Premium",
    selectDate: "Sélectionner la Date",
    travelers: "Voyageurs",
    basePrice: "Prix de Base",
    serviceFee: "Frais de Service",
    bookTripNow: "Réservez Votre Voyage",
    freeCancellation: "Annulation gratuite jusqu'à 48 heures avant le voyage.",
    backToDestinations: "Retour aux Destinations",
    welcomeBack: "Bon Retour",
    enterCredentials: "Entrez vos identifiants pour accéder à vos voyages de luxe",
    email: "Email",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    signIn: "Se Connecter",
    signingIn: "Connexion...",
    noAccount: "Pas de compte ?",
    createAccount: "Créer un Compte",
    joinUs: "Rejoignez Orchids Travel pour des expériences de voyage de luxe exclusives",
    creatingAccount: "Création du compte...",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    flights: "Vols",
    flightsDesc: "Les meilleures offres sur les vols internationaux et diversifiés.",
    tours: "Tours",
    toursDesc: "Forfaits vacances tout compris pour les familles.",
    readyForAdventure: "Prêt pour votre prochaine aventure ?",
    readyForAdventureDesc: "Rejoignez des milliers de voyageurs qui ont trouvé leurs vacances de rêve avec Orchids Travel. Accédez exclusivement à des offres premium et des itinéraires personnalisés.",
    exploreFooter: "Explorer",
    contactFooter: "Contact",
    addDates: "Ajouter des dates",
    search: "Rechercher",
    noDestinationsFound: "Aucune destination trouvée",
    noDestinationsFoundDesc: "Essayez d'ajuster votre recherche ou vos filtres.",
    clearAllFilters: "Effacer Tous les Filtres",
    startingFrom: "À partir de",
    all: "Tous",
    romantic: "Romantique",
    adventure: "Aventure",
    cultural: "Culturel",
    tropical: "Tropical",
    luxury: "Luxe",
    viewAllPackages: "Voir Tous les Forfaits",
    viewAllHotels: "Voir Tous les Hôtels",
    guestReviews: "Avis des Clients",
    reviewsCount: "avis",
    noReviewsYet: "Pas encore d'avis. Soyez le premier à partager votre expérience!",
    writeAReview: "Écrire un Avis",
    loginToReview: "Connectez-vous pour partager votre expérience.",
    reviewPlaceholder: "Partagez votre expérience...",
    submitting: "Envoi...",
    submitReview: "Soumettre l'Avis",
    backToHotels: "Retour aux Hôtels",
    night: "nuit",
    aboutTheHotel: "À Propos de l'Hôtel",
    featuredAmenities: "Équipements en Vedette",
    allAmenities: "Tous les Équipements",
    bestPriceGuaranteed: "Meilleure Prix Garanti",
    bookYourStay: "Réserver Votre Séjour",
    checkAvailability: "Vérifier la Disponibilité",
    freeCancellationHotel: "Annulation gratuite jusqu'à 48h avant l'arrivée",
    backToPackages: "Retour aux Forfaits",
    packageDescription: "Description du Forfait",
    bestValue: "Meilleure Valeur",
    perPackage: "total",
    selectDepartureDate: "Sélectionner la Date de Départ",
    bookPackageNow: "Réserver Ce Forfait",
    customizeItinerary: "Personnaliser l'Itinéraire",
    priceIncludesTax: "Le prix inclut toutes les taxes",
    insuranceIncluded: "Assurance Voyage Incluse",
    destinationNotFound: "Destination Non Trouvée",
    destinationNotFoundDesc: "La destination que vous recherchez n'existe pas.",
    errorInvalidCredentials: "Email ou mot de passe invalide.",
    errorEmailNotConfirmed: "Veuillez confirmer votre adresse email.",
    errorRateLimit: "Trop de tentatives. Veuillez réessayer plus tard.",
    errorUnexpected: "Une erreur inattendue est survenue.",
    checkEmailConfirm: "Veuillez vérifier votre email pour confirmer votre compte.",
  },
  de: {
    home: "Startseite",
    destinations: "Reiseziele",
    hotels: "Hotels",
    packages: "Pakete",
    contact: "Kontakt",
    bookNow: "Jetzt Buchen",
    searchPlaceholder: "Wohin möchten Sie gehen?",
    heroTitle: "Premium Roter Samt Reisen",
    heroSubtitle: "Erleben Sie Luxus wie nie zuvor mit unseren kuratierten Reiseführern.",
    viewDetails: "Details Anzeigen",
    exploreMore: "Mehr Erkunden",
    contactAgent: "Agent Kontaktieren",
    login: "Anmelden",
    signup: "Registrieren",
    profile: "Profil",
    logout: "Abmelden",
    featuredDestinations: "Beliebte Reiseziele",
    popularCategories: "Beliebte Kategorien",
    luxuryStays: "Luxusaufenthalte",
    luxuryStaysDesc: "Kuratierte Sammlung der prestigeträchtigsten Hotels und Resorts der Welt.",
    curatedTourPackages: "Kuratierte Tourpakete",
    curatedTourPackagesDesc: "Handgefertigte Reiserouten, die das Beste aus Luxus, Abenteuer und Kultur vereinen.",
    exclusiveOffers: "Exklusive Angebote",
    bookStay: "Aufenthalt Buchen",
    perNight: "pro Nacht",
    recommended: "Empfohlen",
    allInclusive: "All-Inclusive",
    experienceIndia: "Indien erleben",
    experiencePackages: "Erlebnispakete",
    experiencePackagesDesc: "Kuratierte Reiseerlebnisse für jeden Reisetyp",
    exploreWorld: "Welt erkunden",
    popularDestinations: "Beliebte Reiseziele",
    popularDestinationsDesc: "Entdecken Sie die atemberaubendsten Reiseziele der Welt",
    viewAll: "Alle anzeigen",
    footerDesc: "Die weltweit erste Premium-Reiseplattform für den modernen Abenteurer. Luxus, vereinfacht.",
    privacyPolicy: "Datenschutzrichtlinie",
    termsOfService: "Nutzungsbedingungen",
    allRightsReserved: "Alle Rechte vorbehalten.",
    heritageAndCulture: "Erbe & Kultur",
    heritageAndCultureDesc: "Alte Tempel & Denkmäler",
    adventureAndThrills: "Abenteuer & Nervenkitzel",
    adventureAndThrillsDesc: "Wandern & Extremsport",
    wildlifeSafari: "Wildlife Safari",
    wildlifeSafariDesc: "Nationalparks & Reservate",
    beachAndRelaxation: "Strand & Entspannung",
    beachAndRelaxationDesc: "Küstenausflüge",
    spiritualJourneys: "Spirituelle Reisen",
    spiritualJourneysDesc: "Pilgerreisen & Wellness",
    foodAndCulinary: "Essen & Kulinarik",
    foodAndCulinaryDesc: "Lokale Küchenerlebnisse",
    wifi: "WLAN",
    breakfast: "Frühstück",
    pool: "Pool",
    dining: "Restaurant",
    speakWithSpecialist: "Sprechen Sie mit einem Spezialisten",
    speakWithSpecialistDesc: "Unsere Luxus-Reiseagenten sind bereit, Ihren perfekten Urlaub zu gestalten.",
    emailUs: "E-Mail",
    callAnytime: "Anrufen",
    fullName: "Vollständiger Name",
    emailAddress: "E-Mail-Adresse",
    yourInquiry: "Ihre Anfrage",
    inquiryPlaceholder: "Erzählen Sie uns von Ihrem Traumziel...",
    sendInquiry: "Anfrage Senden",
    sending: "Senden...",
    messageReceived: "Nachricht Erhalten",
    messageReceivedDesc: "Einer unserer Spezialisten wird Sie in Kürze kontaktieren.",
    sendAnotherMessage: "Weitere Nachricht Senden",
    confirmBooking: "Bestätigen Sie Ihre Buchung",
    travelDates: "Reisedaten",
    numberOfTravelers: "Anzahl der Reisenden",
    paymentDetails: "Zahlungsdetails",
    cardholderName: "Name des Karteninhabers",
    cardNumber: "Kartennummer",
    processing: "Verarbeitung...",
    completeBooking: "Buchung Abschließen",
    baseFare: "Grundpreis",
    taxesFees: "Steuern & Gebühren",
    total: "Gesamt",
    secureCheckout: "Sichere Zahlung",
    welcome: "Willkommen",
    accountSettings: "Kontoeinstellungen",
    memberBenefits: "Mitgliedsvorteile",
    premiumStatus: "Premium-Status",
    exclusiveOffersAvailable: "Exklusive Angebote verfügbar",
    travelCreditAvailable: "Reiseguthaben verfügbar",
    planNextTrip: "Planen Sie Ihre nächste Reise",
    planNextTripDesc: "Entdecken Sie unsere neu hinzugefügten Ziele für Winter 2024.",
    myBookings: "Meine Buchungen",
    newBooking: "Neue Buchung",
    viewDetailsBtn: "Details Anzeigen",
    noBookingsYet: "Sie haben noch keine Reisen gebucht.",
    bookFirstTrip: "Buchen Sie Ihre Erste Reise",
    aboutJourney: "Über diese Reise",
    journeyHighlights: "Reise-Highlights",
    whatsIncluded: "Was enthalten ist",
    premiumPackage: "Premium-Paket",
    selectDate: "Datum Auswählen",
    travelers: "Reisende",
    basePrice: "Grundpreis",
    serviceFee: "Servicegebühr",
    bookTripNow: "Jetzt Reise Buchen",
    freeCancellation: "Kostenlose Stornierung bis 48 Stunden vor der Reise.",
    backToDestinations: "Zurück zu Reisezielen",
    welcomeBack: "Willkommen Zurück",
    enterCredentials: "Geben Sie Ihre Anmeldedaten ein, um auf Ihre Luxusreisen zuzugreifen",
    email: "E-Mail",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",
    signIn: "Anmelden",
    signingIn: "Anmeldung...",
    noAccount: "Kein Konto?",
    createAccount: "Konto Erstellen",
    joinUs: "Treten Sie Orchids Travel für exklusive Luxusreiseerlebnisse bei",
    creatingAccount: "Konto wird erstellt...",
    alreadyHaveAccount: "Haben Sie bereits ein Konto?",
    flights: "Flüge",
    flightsDesc: "Beste Angebote für internationale und inländische Flüge.",
    tours: "Touren",
    toursDesc: "All-Inclusive-Urlaubspakete für Familien.",
    readyForAdventure: "Bereit für Ihr nächstes Abenteuer?",
    readyForAdventureDesc: "Schließen Sie sich Tausenden von Reisenden an, die ihren Traumurlaub mit Orchids Travel gefunden haben. Erhalten Sie exklusiven Zugang zu Premium-Angeboten und personalisierten Reiserouten.",
    exploreFooter: "Erkunden",
    contactFooter: "Kontakt",
    addDates: "Daten hinzufügen",
    search: "Suchen",
    noDestinationsFound: "Keine Reiseziele gefunden",
    noDestinationsFoundDesc: "Versuchen Sie, Ihre Suche oder Filter anzupassen.",
    clearAllFilters: "Alle Filter Löschen",
    startingFrom: "Ab",
    all: "Alle",
    romantic: "Romantisch",
    adventure: "Abenteuer",
    cultural: "Kulturell",
    tropical: "Tropisch",
    luxury: "Luxus",
    viewAllPackages: "Alle Pakete Anzeigen",
    viewAllHotels: "Alle Hotels Anzeigen",
    guestReviews: "Gästebewertungen",
    reviewsCount: "Bewertungen",
    noReviewsYet: "Noch keine Bewertungen. Seien Sie der Erste!",
    writeAReview: "Bewertung Schreiben",
    loginToReview: "Melden Sie sich an, um Ihre Erfahrung zu teilen.",
    reviewPlaceholder: "Teilen Sie Ihre Erfahrung...",
    submitting: "Senden...",
    submitReview: "Bewertung Absenden",
    backToHotels: "Zurück zu Hotels",
    night: "Nacht",
    aboutTheHotel: "Über das Hotel",
    featuredAmenities: "Ausstattungs-Highlights",
    allAmenities: "Alle Annehmlichkeiten",
    bestPriceGuaranteed: "Bestpreis Garantiert",
    bookYourStay: "Aufenthalt Buchen",
    checkAvailability: "Verfügbarkeit Prüfen",
    freeCancellationHotel: "Kostenlose Stornierung bis 48h vor Check-in",
    backToPackages: "Zurück zu Paketen",
    packageDescription: "Paketbeschreibung",
    bestValue: "Bester Wert",
    perPackage: "gesamt",
    selectDepartureDate: "Abreisedatum Wählen",
    bookPackageNow: "Dieses Paket Buchen",
    customizeItinerary: "Reiseplan Anpassen",
    priceIncludesTax: "Preis inklusive aller Steuern",
    insuranceIncluded: "Reiseversicherung Inklusive",
    destinationNotFound: "Reiseziel Nicht Gefunden",
    destinationNotFoundDesc: "Das gesuchte Reiseziel existiert nicht.",
    errorInvalidCredentials: "Ungültige E-Mail oder Passwort.",
    errorEmailNotConfirmed: "Bitte bestätigen Sie Ihre E-Mail-Adresse.",
    errorRateLimit: "Zu viele Versuche. Bitte versuchen Sie es später noch einmal.",
    errorUnexpected: "Ein unerwarteter Fehler ist aufgetreten.",
    checkEmailConfirm: "Bitte überprüfen Sie Ihre E-Mail, um Ihr Konto zu bestätigen.",
  },
  hi: {
    home: "होम",
    destinations: "गंतव्य",
    hotels: "होटल",
    packages: "पैकेज",
    contact: "संपर्क",
    bookNow: "अभी बुक करें",
    searchPlaceholder: "आप कहाँ जाना चाहते हैं?",
    heroTitle: "प्रीमियम रेड वेलवेट ट्रैवल",
    heroSubtitle: "हमारे क्यूरेटेड ट्रैवल गाइड्स के साथ पहले जैसा लक्ज़री अनुभव करें।",
    viewDetails: "विवरण देखें",
    exploreMore: "और देखें",
    contactAgent: "एजेंट से संपर्क करें",
    login: "लॉग इन",
    signup: "साइन अप",
    profile: "प्रोफ़ाइल",
    logout: "लॉग आउट",
    featuredDestinations: "लोकप्रिय गंतव्य",
    popularCategories: "लोकप्रिय श्रेणियां",
    luxuryStays: "लक्ज़री स्टे",
    luxuryStaysDesc: "दुनिया के सबसे प्रतिष्ठित होटलों और रिसॉर्ट्स का क्यूरेटेड संग्रह।",
    curatedTourPackages: "क्यूरेटेड टूर पैकेज",
    curatedTourPackagesDesc: "लक्ज़री, एडवेंचर और संस्कृति का सर्वश्रेष्ठ मिश्रण।",
    exclusiveOffers: "विशेष ऑफ़र",
    bookStay: "स्टे बुक करें",
    perNight: "प्रति रात",
    recommended: "अनुशंसित",
    allInclusive: "सब कुछ शामिल",
    experienceIndia: "भारत का अनुभव",
    experiencePackages: "अनुभव पैकेज",
    experiencePackagesDesc: "हर प्रकार के यात्री के लिए क्यूरेटेड यात्रा अनुभव",
    exploreWorld: "दुनिया देखें",
    popularDestinations: "लोकप्रिय गंतव्य",
    popularDestinationsDesc: "दुनिया के सबसे खूबसूरत गंतव्यों की खोज करें",
    viewAll: "सभी देखें",
    footerDesc: "आधुनिक साहसी के लिए डिज़ाइन किया गया दुनिया का पहला प्रीमियम ट्रैवल प्लेटफ़ॉर्म। लक्ज़री, सरलीकृत।",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    heritageAndCulture: "विरासत और संस्कृति",
    heritageAndCultureDesc: "प्राचीन मंदिर और स्मारक",
    adventureAndThrills: "एडवेंचर और रोमांच",
    adventureAndThrillsDesc: "ट्रेकिंग और एक्सट्रीम स्पोर्ट्स",
    wildlifeSafari: "वाइल्डलाइफ सफारी",
    wildlifeSafariDesc: "राष्ट्रीय उद्यान और अभयारण्य",
    beachAndRelaxation: "बीच और आराम",
    beachAndRelaxationDesc: "तटीय गेटअवे",
    spiritualJourneys: "आध्यात्मिक यात्राएं",
    spiritualJourneysDesc: "तीर्थयात्रा और वेलनेस",
    foodAndCulinary: "खाना और पाक कला",
    foodAndCulinaryDesc: "स्थानीय व्यंजन अनुभव",
    wifi: "वाईफ़ाई",
    breakfast: "नाश्ता",
    pool: "पूल",
    dining: "भोजन",
    speakWithSpecialist: "विशेषज्ञ से बात करें",
    speakWithSpecialistDesc: "हमारे लक्ज़री ट्रैवल एजेंट आपकी परफेक्ट छुट्टी बनाने के लिए तैयार हैं।",
    emailUs: "ईमेल करें",
    callAnytime: "कॉल करें",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    yourInquiry: "आपकी पूछताछ",
    inquiryPlaceholder: "अपने सपनों की मंज़िल के बारे में बताएं...",
    sendInquiry: "पूछताछ भेजें",
    sending: "भेजा जा रहा है...",
    messageReceived: "संदेश प्राप्त हुआ",
    messageReceivedDesc: "हमारे विशेषज्ञ जल्द ही आपसे संपर्क करेंगे।",
    sendAnotherMessage: "एक और संदेश भेजें",
    confirmBooking: "बुकिंग की पुष्टि करें",
    travelDates: "यात्रा तिथियां",
    numberOfTravelers: "यात्रियों की संख्या",
    paymentDetails: "भुगतान विवरण",
    cardholderName: "कार्डधारक का नाम",
    cardNumber: "कार्ड नंबर",
    processing: "प्रोसेसिंग...",
    completeBooking: "बुकिंग पूरी करें",
    baseFare: "बेस किराया",
    taxesFees: "टैक्स और शुल्क",
    total: "कुल",
    secureCheckout: "सुरक्षित चेकआउट",
    welcome: "स्वागत है",
    accountSettings: "खाता सेटिंग्स",
    memberBenefits: "सदस्य लाभ",
    premiumStatus: "प्रीमियम स्टेटस",
    exclusiveOffersAvailable: "विशेष ऑफ़र उपलब्ध",
    travelCreditAvailable: "ट्रैवल क्रेडिट उपलब्ध",
    planNextTrip: "अगली यात्रा की योजना बनाएं",
    planNextTripDesc: "विंटर 2024 के लिए हमारे नए गंतव्य देखें।",
    myBookings: "मेरी बुकिंग्स",
    newBooking: "नई बुकिंग",
    viewDetailsBtn: "विवरण देखें",
    noBookingsYet: "आपने अभी तक कोई यात्रा बुक नहीं की है।",
    bookFirstTrip: "अपनी पहली यात्रा बुक करें",
    aboutJourney: "इस यात्रा के बारे में",
    journeyHighlights: "यात्रा की मुख्य विशेषताएं",
    whatsIncluded: "क्या शामिल है",
    premiumPackage: "प्रीमियम पैकेज",
    selectDate: "तारीख चुनें",
    travelers: "यात्री",
    basePrice: "बेस प्राइस",
    serviceFee: "सर्विस फ़ीस",
    bookTripNow: "अभी यात्रा बुक करें",
    freeCancellation: "यात्रा से 48 घंटे पहले तक मुफ्त कैंसलेशन।",
    backToDestinations: "गंतव्यों पर वापस जाएं",
    welcomeBack: "वापसी पर स्वागत है",
    enterCredentials: "अपनी लक्ज़री यात्राओं तक पहुंचने के लिए क्रेडेंशियल दर्ज करें",
    email: "ईमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    signIn: "साइन इन",
    signingIn: "साइन इन हो रहा है...",
    noAccount: "खाता नहीं है?",
    createAccount: "खाता बनाएं",
    joinUs: "विशेष लक्ज़री ट्रैवल अनुभवों के लिए Orchids Travel से जुड़ें",
    creatingAccount: "खाता बनाया जा रहा है...",
    alreadyHaveAccount: "पहले से खाता है?",
    flights: "फ्लाइट्स",
    flightsDesc: "अंतर्राष्ट्रीय और घरेलू उड़ानों पर सर्वश्रेष्ठ डील।",
    tours: "टूर्स",
    toursDesc: "परिवारों के लिए ऑल-इनक्लूसिव वेकेशन पैकेज।",
    readyForAdventure: "अपने अगले एडवेंचर के लिए तैयार हैं?",
    readyForAdventureDesc: "Orchids Travel के साथ हजारों यात्रियों से जुड़ें जिन्होंने अपनी सपनों की छुट्टी पाई है।",
    exploreFooter: "एक्सप्लोर",
    contactFooter: "संपर्क",
    addDates: "तारीखें जोड़ें",
    search: "खोजें",
    noDestinationsFound: "कोई गंतव्य नहीं मिला",
    noDestinationsFoundDesc: "अपनी खोज या फ़िल्टर समायोजित करने का प्रयास करें।",
    clearAllFilters: "सभी फ़िल्टर हटाएं",
    startingFrom: "से शुरू",
    all: "सभी",
    romantic: "रोमांटिक",
    adventure: "एडवेंचर",
    cultural: "सांस्कृतिक",
    tropical: "उष्णकटिबंधीय",
    luxury: "लक्ज़री",
    viewAllPackages: "सभी पैकेज देखें",
    viewAllHotels: "सभी होटल देखें",
    guestReviews: "अतिथि समीक्षाएं",
    reviewsCount: "समीक्षाएं",
    noReviewsYet: "अभी कोई समीक्षा नहीं। पहले बनें!",
    writeAReview: "समीक्षा लिखें",
    loginToReview: "अपना अनुभव साझा करने के लिए लॉग इन करें।",
    reviewPlaceholder: "अपना अनुभव साझा करें...",
    submitting: "सबमिट हो रहा है...",
    submitReview: "समीक्षा सबमिट करें",
    backToHotels: "होटलों पर वापस जाएं",
    night: "रात",
    aboutTheHotel: "होटल के बारे में",
    featuredAmenities: "विशेष सुविधाएं",
    allAmenities: "सभी सुविधाएं",
    bestPriceGuaranteed: "सर्वोत्तम मूल्य गारंटी",
    bookYourStay: "अपना स्टे बुक करें",
    checkAvailability: "उपलब्धता जांचें",
    freeCancellationHotel: "चेक-इन से 48 घंटे पहले तक मुफ्त कैंसलेशन",
    backToPackages: "पैकेज पर वापस जाएं",
    packageDescription: "पैकेज विवरण",
    bestValue: "सर्वश्रेष्ठ मूल्य",
    perPackage: "कुल",
    selectDepartureDate: "प्रस्थान तिथि चुनें",
    bookPackageNow: "यह पैकेज बुक करें",
    customizeItinerary: "इटिनरेरी कस्टमाइज़ करें",
    priceIncludesTax: "कीमत में सभी टैक्स शामिल",
    insuranceIncluded: "ट्रैवल इंश्योरेंस शामिल",
    destinationNotFound: "गंतव्य नहीं मिला",
    destinationNotFoundDesc: "आप जिस गंतव्य की तलाश कर रहे हैं वह मौजूद नहीं है।",
    errorInvalidCredentials: "अमान्य ईमेल या पासवर्ड।",
    errorEmailNotConfirmed: "कृपया अपना ईमेल पता पुष्ट करें।",
    errorRateLimit: "बहुत अधिक प्रयास। कृपया बाद में पुनः प्रयास करें।",
    errorUnexpected: "एक अप्रत्याशित त्रुटि हुई।",
    checkEmailConfirm: "अपना खाता पुष्ट करने के लिए कृपया अपना ईमेल जांचें।",
  },
  ta: {
    home: "முகப்பு",
    destinations: "சேருமிடங்கள்",
    hotels: "ஹோட்டல்கள்",
    packages: "பேக்கேஜ்கள்",
    contact: "தொடர்பு",
    bookNow: "இப்போதே புக் செய்யுங்கள்",
    searchPlaceholder: "எங்கு செல்ல விரும்புகிறீர்கள்?",
    heroTitle: "பிரீமியம் ரெட் வெல்வெட் பயணம்",
    heroSubtitle: "எங்கள் தேர்ந்தெடுக்கப்பட்ட பயண வழிகாட்டிகளுடன் ஆடம்பரத்தை அனுபவியுங்கள்.",
    viewDetails: "விவரங்களைக் காண்க",
    exploreMore: "மேலும் ஆராயுங்கள்",
    contactAgent: "ஏஜென்ட்டைத் தொடர்பு கொள்ளுங்கள்",
    login: "உள்நுழைவு",
    signup: "பதிவு",
    profile: "சுயவிவரம்",
    logout: "வெளியேறு",
    featuredDestinations: "சிறப்பு சேருமிடங்கள்",
    popularCategories: "பிரபலமான வகைகள்",
    luxuryStays: "ஆடம்பர தங்குமிடங்கள்",
    luxuryStaysDesc: "உலகின் மிகவும் புகழ்பெற்ற ஹோட்டல்கள் மற்றும் ரிசார்ட்களின் தொகுப்பு.",
    curatedTourPackages: "தேர்ந்தெடுக்கப்பட்ட டூர் பேக்கேஜ்கள்",
    curatedTourPackagesDesc: "ஆடம்பரம், சாகசம் மற்றும் கலாச்சாரத்தின் சிறந்த கலவை.",
    exclusiveOffers: "பிரத்யேக சலுகைகள்",
    bookStay: "தங்குமிடம் புக் செய்யுங்கள்",
    perNight: "ஒரு இரவுக்கு",
    recommended: "பரிந்துரைக்கப்பட்டது",
    allInclusive: "அனைத்தும் உள்ளடக்கியது",
    experienceIndia: "இந்தியாவை அனுபவியுங்கள்",
    experiencePackages: "அனுபவ பேக்கேஜ்கள்",
    experiencePackagesDesc: "எல்லா வகையான பயணிகளுக்கும் தேர்ந்தெடுக்கப்பட்ட பயண அனுபவங்கள்",
    exploreWorld: "உலகை ஆராயுங்கள்",
    popularDestinations: "பிரபலமான சேருமிடங்கள்",
    popularDestinationsDesc: "உலகின் மிகவும் அழகான சேருமிடங்களைக் கண்டறியுங்கள்",
    viewAll: "அனைத்தையும் காண்க",
    footerDesc: "நவீன சாகசக்காரர்களுக்காக வடிவமைக்கப்பட்ட உலகின் முதல் பிரீமியம் பயண தளம். ஆடம்பரம், எளிமையாக்கப்பட்டது.",
    privacyPolicy: "தனியுரிமைக் கொள்கை",
    termsOfService: "சேவை விதிமுறைகள்",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    heritageAndCulture: "பாரம்பரியம் & கலாச்சாரம்",
    heritageAndCultureDesc: "பழங்கால கோயில்கள் & நினைவுச்சின்னங்கள்",
    adventureAndThrills: "சாகசம் & த்ரில்ஸ்",
    adventureAndThrillsDesc: "டிரெக்கிங் & எக்ஸ்ட்ரீம் ஸ்போர்ட்ஸ்",
    wildlifeSafari: "வனவிலங்கு சஃபாரி",
    wildlifeSafariDesc: "தேசிய பூங்காக்கள் & சரணாலயங்கள்",
    beachAndRelaxation: "கடற்கரை & ஓய்வு",
    beachAndRelaxationDesc: "கடற்கரை விடுமுறைகள்",
    spiritualJourneys: "ஆன்மீக பயணங்கள்",
    spiritualJourneysDesc: "புனித யாத்திரை & நல்வாழ்வு",
    foodAndCulinary: "உணவு & சமையல்",
    foodAndCulinaryDesc: "உள்ளூர் உணவு அனுபவங்கள்",
    wifi: "வைஃபை",
    breakfast: "காலை உணவு",
    pool: "நீச்சல் குளம்",
    dining: "உணவகம்",
    speakWithSpecialist: "நிபுணருடன் பேசுங்கள்",
    speakWithSpecialistDesc: "எங்கள் ஆடம்பர பயண முகவர்கள் உங்கள் சரியான விடுமுறையை உருவாக்க தயாராக உள்ளனர்.",
    emailUs: "மின்னஞ்சல் அனுப்புங்கள்",
    callAnytime: "அழைக்கவும்",
    fullName: "முழு பெயர்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    yourInquiry: "உங்கள் விசாரணை",
    inquiryPlaceholder: "உங்கள் கனவு இடத்தைப் பற்றி சொல்லுங்கள்...",
    sendInquiry: "விசாரணை அனுப்புங்கள்",
    sending: "அனுப்புகிறது...",
    messageReceived: "செய்தி பெறப்பட்டது",
    messageReceivedDesc: "எங்கள் நிபுணர் விரைவில் உங்களைத் தொடர்பு கொள்வார்.",
    sendAnotherMessage: "மற்றொரு செய்தி அனுப்புங்கள்",
    confirmBooking: "புக்கிங்கை உறுதிப்படுத்துங்கள்",
    travelDates: "பயண தேதிகள்",
    numberOfTravelers: "பயணிகள் எண்ணிக்கை",
    paymentDetails: "பணம் செலுத்தும் விவரங்கள்",
    cardholderName: "கார்டுதாரரின் பெயர்",
    cardNumber: "கார்டு எண்",
    processing: "செயலாக்குகிறது...",
    completeBooking: "புக்கிங்கை முடிக்கவும்",
    baseFare: "அடிப்படை கட்டணம்",
    taxesFees: "வரிகள் & கட்டணங்கள்",
    total: "மொத்தம்",
    secureCheckout: "பாதுகாப்பான செக்அவுட்",
    welcome: "வரவேற்கிறோம்",
    accountSettings: "கணக்கு அமைப்புகள்",
    memberBenefits: "உறுப்பினர் நன்மைகள்",
    premiumStatus: "பிரீமியம் நிலை",
    exclusiveOffersAvailable: "பிரத்யேக சலுகைகள் கிடைக்கும்",
    travelCreditAvailable: "பயண கிரெடிட் கிடைக்கும்",
    planNextTrip: "அடுத்த பயணத்தைத் திட்டமிடுங்கள்",
    planNextTripDesc: "குளிர்காலம் 2024க்கான புதிய சேருமிடங்களைக் காணுங்கள்.",
    myBookings: "எனது புக்கிங்குகள்",
    newBooking: "புதிய புக்கிங்",
    viewDetailsBtn: "விவரங்களைக் காண்க",
    noBookingsYet: "நீங்கள் இன்னும் எந்த பயணமும் புக் செய்யவில்லை.",
    bookFirstTrip: "உங்கள் முதல் பயணத்தை புக் செய்யுங்கள்",
    aboutJourney: "இந்த பயணம் பற்றி",
    journeyHighlights: "பயண சிறப்பம்சங்கள்",
    whatsIncluded: "என்ன உள்ளடக்கியது",
    premiumPackage: "பிரீமியம் பேக்கேஜ்",
    selectDate: "தேதி தேர்ந்தெடுக்கவும்",
    travelers: "பயணிகள்",
    basePrice: "அடிப்படை விலை",
    serviceFee: "சேவை கட்டணம்",
    bookTripNow: "இப்போது பயணத்தை புக் செய்யுங்கள்",
    freeCancellation: "பயணத்திற்கு 48 மணி நேரத்திற்கு முன் இலவச ரத்து.",
    backToDestinations: "சேருமிடங்களுக்குத் திரும்பு",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    enterCredentials: "உங்கள் ஆடம்பர பயணங்களை அணுக உள்நுழைக",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    signIn: "உள்நுழைக",
    signingIn: "உள்நுழைகிறது...",
    noAccount: "கணக்கு இல்லையா?",
    createAccount: "கணக்கை உருவாக்குங்கள்",
    joinUs: "பிரத்யேக ஆடம்பர பயண அனுபவங்களுக்கு Orchids Travel இல் சேரவும்",
    creatingAccount: "கணக்கை உருவாக்குகிறது...",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    flights: "விமானங்கள்",
    flightsDesc: "சர்வதேச மற்றும் உள்நாட்டு விமானங்களில் சிறந்த சலுகைகள்.",
    tours: "சுற்றுப்பயணங்கள்",
    toursDesc: "குடும்பங்களுக்கான ஆல்-இன்க்ளூசிவ் விடுமுறை பேக்கேஜ்கள்.",
    readyForAdventure: "உங்கள் அடுத்த சாகசத்திற்கு தயாரா?",
    readyForAdventureDesc: "Orchids Travel உடன் கனவு விடுமுறையைக் கண்டறிந்த ஆயிரக்கணக்கான பயணிகளுடன் சேருங்கள்.",
    exploreFooter: "ஆராய்க",
    contactFooter: "தொடர்பு",
    addDates: "தேதிகளைச் சேர்க்கவும்",
    search: "தேடு",
    noDestinationsFound: "சேருமிடங்கள் இல்லை",
    noDestinationsFoundDesc: "உங்கள் தேடல் அல்லது வடிப்பான்களை சரிசெய்ய முயற்சிக்கவும்.",
    clearAllFilters: "அனைத்து வடிப்பான்களையும் அழிக்கவும்",
    startingFrom: "தொடக்கம்",
    all: "அனைத்தும்",
    romantic: "காதல்",
    adventure: "சாகசம்",
    cultural: "கலாச்சாரம்",
    tropical: "வெப்பமண்டலம்",
    luxury: "ஆடம்பரம்",
    viewAllPackages: "அனைத்து பேக்கேஜ்களையும் காண்க",
    viewAllHotels: "அனைத்து ஹோட்டல்களையும் காண்க",
    guestReviews: "விருந்தினர் மதிப்புரைகள்",
    reviewsCount: "மதிப்புரைகள்",
    noReviewsYet: "இன்னும் மதிப்புரைகள் இல்லை. முதல்வராக இருங்கள்!",
    writeAReview: "மதிப்புரை எழுதுங்கள்",
    loginToReview: "உங்கள் அனுபவத்தைப் பகிர உள்நுழையவும்.",
    reviewPlaceholder: "உங்கள் அனுபவத்தைப் பகிருங்கள்...",
    submitting: "சமர்ப்பிக்கிறது...",
    submitReview: "மதிப்புரை சமர்ப்பிக்கவும்",
    backToHotels: "ஹோட்டல்களுக்குத் திரும்பு",
    night: "இரவு",
    aboutTheHotel: "ஹோட்டலைப் பற்றி",
    featuredAmenities: "சிறப்பு வசதிகள்",
    allAmenities: "அனைத்து வசதிகள்",
    bestPriceGuaranteed: "சிறந்த விலை உத்தரவாதம்",
    bookYourStay: "உங்கள் தங்குமிடத்தை புக் செய்யுங்கள்",
    checkAvailability: "கிடைக்கும் தன்மையைச் சரிபார்க்கவும்",
    freeCancellationHotel: "செக்-இன் முன் 48 மணி நேரம் வரை இலவச ரத்து",
    backToPackages: "பேக்கேஜ்களுக்குத் திரும்பு",
    packageDescription: "பேக்கேஜ் விவரம்",
    bestValue: "சிறந்த மதிப்பு",
    perPackage: "மொத்தம்",
    selectDepartureDate: "புறப்படும் தேதியைத் தேர்ந்தெடுக்கவும்",
    bookPackageNow: "இந்த பேக்கேஜை புக் செய்யுங்கள்",
    customizeItinerary: "பயணத்திட்டத்தைத் தனிப்பயனாக்குங்கள்",
    priceIncludesTax: "விலையில் அனைத்து வரிகளும் அடங்கும்",
    insuranceIncluded: "பயண காப்பீடு உள்ளடக்கியது",
    destinationNotFound: "சேருமிடம் கிடைக்கவில்லை",
    destinationNotFoundDesc: "நீங்கள் தேடும் சேருமிடம் இல்லை.",
    errorInvalidCredentials: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.",
    errorEmailNotConfirmed: "உங்கள் மின்னஞ்சல் முகவரியை உறுதிப்படுத்தவும்.",
    errorRateLimit: "அதிகப்படியான முயற்சிகள். பிறகு முயற்சிக்கவும்.",
    errorUnexpected: "எதிர்பாராத பிழை ஏற்பட்டது.",
    checkEmailConfirm: "உங்கள் கணக்கை உறுதிப்படுத்த உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்.",
  },
  te: {
    home: "హోమ్",
    destinations: "గమ్యస్థానాలు",
    hotels: "హోటళ్లు",
    packages: "ప్యాకేజీలు",
    contact: "సంప్రదించండి",
    bookNow: "ఇప్పుడే బుక్ చేయండి",
    searchPlaceholder: "మీరు ఎక్కడికి వెళ్లాలనుకుంటున్నారు?",
    heroTitle: "ప్రీమియం రెడ్ వెల్వెట్ ట్రావెల్",
    heroSubtitle: "మా క్యూరేటెడ్ ట్రావెల్ గైడ్‌లతో లగ్జరీని అనుభవించండి.",
    viewDetails: "వివరాలు చూడండి",
    exploreMore: "మరింత అన్వేషించండి",
    contactAgent: "ఏజెంట్‌ను సంప్రదించండి",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    profile: "ప్రొఫైల్",
    logout: "లాగ్ అవుట్",
    featuredDestinations: "ఫీచర్డ్ గమ్యస్థానాలు",
    popularCategories: "ప్రసిద్ధ వర్గాలు",
    luxuryStays: "లగ్జరీ స్టేలు",
    luxuryStaysDesc: "ప్రపంచంలోని అత్యంత ప్రతిష్ఠాత్మక హోటళ్లు మరియు రిసార్ట్‌ల సేకరణ.",
    curatedTourPackages: "క్యూరేటెడ్ టూర్ ప్యాకేజీలు",
    curatedTourPackagesDesc: "లగ్జరీ, సాహసం మరియు సంస్కృతి యొక్క ఉత్తమ మిశ్రమం.",
    exclusiveOffers: "ప్రత్యేక ఆఫర్లు",
    bookStay: "స్టే బుక్ చేయండి",
    perNight: "రాత్రికి",
    recommended: "సిఫార్సు చేయబడింది",
    allInclusive: "అన్నీ కలిసి",
    experienceIndia: "భారతదేశాన్ని అనుభవించండి",
    experiencePackages: "అనుభవ ప్యాకేజీలు",
    experiencePackagesDesc: "ప్రతి రకమైన ప్రయాణికుడికి క్యూరేటెడ్ ప్రయాణ అనుభవాలు",
    exploreWorld: "ప్రపంచాన్ని అన్వేషించండి",
    popularDestinations: "ప్రసిద్ధ గమ్యస్థానాలు",
    popularDestinationsDesc: "ప్రపంచంలోని అత్యంత అద్భుతమైన గమ్యస్థానాలను కనుగొనండి",
    viewAll: "అన్నీ చూడండి",
    footerDesc: "ఆధునిక సాహసికుడికి రూపొందించబడిన ప్రపంచంలోని మొదటి ప్రీమియం ట్రావెల్ ప్లాట్‌ఫామ్. లగ్జరీ, సరళీకృతం.",
    privacyPolicy: "గోప్యతా విధానం",
    termsOfService: "సేవా నిబంధనలు",
    allRightsReserved: "అన్ని హక్కులు రిజర్వు చేయబడ్డాయి.",
    heritageAndCulture: "వారసత్వం & సంస్కృతి",
    heritageAndCultureDesc: "పురాతన ఆలయాలు & స్మారక చిహ్నాలు",
    adventureAndThrills: "సాహసం & థ్రిల్స్",
    adventureAndThrillsDesc: "ట్రెక్కింగ్ & ఎక్స్ట్రీమ్ స్పోర్ట్స్",
    wildlifeSafari: "వైల్డ్‌లైఫ్ సఫారి",
    wildlifeSafariDesc: "జాతీయ ఉద్యానవనాలు & రిజర్వులు",
    beachAndRelaxation: "బీచ్ & విశ్రాంతి",
    beachAndRelaxationDesc: "తీర ప్రాంత విడిది",
    spiritualJourneys: "ఆధ్యాత్మిక యాత్రలు",
    spiritualJourneysDesc: "తీర్థయాత్ర & శ్రేయస్సు",
    foodAndCulinary: "ఆహారం & వంటకళ",
    foodAndCulinaryDesc: "స్థానిక వంటకాల అనుభవాలు",
    wifi: "వైఫై",
    breakfast: "అల్పాహారం",
    pool: "స్విమ్మింగ్ పూల్",
    dining: "భోజనశాల",
    speakWithSpecialist: "నిపుణుడితో మాట్లాడండి",
    speakWithSpecialistDesc: "మా లగ్జరీ ట్రావెల్ ఏజెంట్లు మీ పర్ఫెక్ట్ సెలవుని రూపొందించడానికి సిద్ధంగా ఉన్నారు.",
    emailUs: "ఇమెయిల్ చేయండి",
    callAnytime: "కాల్ చేయండి",
    fullName: "పూర్తి పేరు",
    emailAddress: "ఇమెయిల్ చిరునామా",
    yourInquiry: "మీ విచారణ",
    inquiryPlaceholder: "మీ కల గమ్యస్థానం గురించి చెప్పండి...",
    sendInquiry: " విచారణ పంపండి",
    sending: "పంపుతోంది...",
    messageReceived: "సందేశం అందింది",
    messageReceivedDesc: "మా నిపుణులు త్వరలో మిమ్మల్ని సంప్రదిస్తారు.",
    sendAnotherMessage: "మరో సందేశం పంపండి",
    confirmBooking: "బుకింగ్ నిర్ధారించండి",
    travelDates: "ప్రయాణ తేదీలు",
    numberOfTravelers: "ప్రయాణికుల సంఖ్య",
    paymentDetails: "చెల్లింపు వివరాలు",
    cardholderName: "కార్డ్ హోల్డర్ పేరు",
    cardNumber: "కార్డ్ నంబర్",
    processing: "ప్రాసెస్ అవుతోంది...",
    completeBooking: "బుకింగ్ పూర్తి చేయండి",
    baseFare: "బేస్ ఫేర్",
    taxesFees: "పన్నులు & ఫీజులు",
    total: "మొత్తం",
    secureCheckout: "సురక్షిత చెక్అవుట్",
    welcome: "స్వాగతం",
    accountSettings: "ఖాతా సెట్టింగ్స్",
    memberBenefits: "సభ్య ప్రయోజనాలు",
    premiumStatus: "ప్రీమియం స్థితి",
    exclusiveOffersAvailable: "ప్రత్యేక ఆఫర్లు అందుబాటులో ఉన్నాయి",
    travelCreditAvailable: "ట్రావెల్ క్రెడిట్ అందుబాటులో ఉంది",
    planNextTrip: "తదుపరి యాత్ర ప్లాన్ చేయండి",
    planNextTripDesc: "శీతాకాలం 2024 కోసం మా కొత్త గమ్యస్థానాలను చూడండి.",
    myBookings: "నా బుకింగ్‌లు",
    newBooking: "కొత్త బుకింగ్",
    viewDetailsBtn: "వివరాలు చూడండి",
    noBookingsYet: "మీరు ఇంకా ఏ యాత్రను బుక్ చేయలేదు.",
    bookFirstTrip: "మీ మొదటి యాత్ర బుక్ చేయండి",
    aboutJourney: "ఈ యాత్ర గురించి",
    journeyHighlights: "యాత్ర హైలైట్స్",
    whatsIncluded: "ఏమి చేర్చబడింది",
    premiumPackage: "ప్రీమియం ప్యాకేజీ",
    selectDate: "తేదీ ఎంచుకోండి",
    travelers: "ప్రయాణికులు",
    basePrice: "బేస్ ప్రైస్",
    serviceFee: "సర్వీస్ ఫీ",
    bookTripNow: "ఇప్పుడే యాత్ర బుక్ చేయండి",
    freeCancellation: "యాత్రకు 48 గంటల ముందు వరకు ఉచిత రద్దు.",
    backToDestinations: "గమ్యస్థానాలకు తిరిగి వెళ్ళండి",
    welcomeBack: "తిరిగి స్వాగతం",
    enterCredentials: "మీ లగ్జరీ యాత్రలను యాక్సెస్ చేయడానికి క్రెడెన్షియల్స్ నమోదు చేయండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    signIn: "సైన్ ఇన్",
    signingIn: "సైన్ ఇన్ అవుతోంది...",
    noAccount: "ఖాతా లేదా?",
    createAccount: "ఖాతా సృష్టించండి",
    joinUs: "ప్రత్యేక లగ్జరీ ట్రావెల్ అనుభవాల కోసం Orchids Travel లో చేరండి",
    creatingAccount: "ఖాతా సృష్టిస్తోంది...",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    flights: "విమానాలు",
    flightsDesc: "అంతర్జాతీయ మరియు దేశీయ విమానాలపై ఉత్తమ డీల్స్.",
    tours: "టూర్లు",
    toursDesc: "కుటుంబాలకు ఆల్-ఇన్‌క్లూసివ్ వేకేషన్ ప్యాకేజీలు.",
    readyForAdventure: "మీ తదుపరి సాహసానికి సిద్ధమా?",
    readyForAdventureDesc: "Orchids Travel తో కల సెలవును కనుగొన్న వేలాది యాత్రికులతో చేరండి.",
    exploreFooter: "అన్వేషించండి",
    contactFooter: "సంప్రదించండి",
    addDates: "తేదీలు జోడించండి",
    search: "శోధించండి",
    noDestinationsFound: "గమ్యస్థానాలు కనుగొనబడలేదు",
    noDestinationsFoundDesc: "మీ శోధన లేదా ఫిల్టర్లను సర్దుబాటు చేయడానికి ప్రయత్ండిండి.",
    clearAllFilters: "అన్ని ఫిల్టర్లను క్లియర్ చేయండి",
    startingFrom: "నుండి",
    all: "అన్నీ",
    romantic: "రొమాంటిక్",
    adventure: "సాహసం",
    cultural: "సాంస్కృతిక",
    tropical: "ఉష్ణమండల",
    luxury: "లగ్జరీ",
    viewAllPackages: "అన్ని ప్యాకేజీలు చూడండి",
    viewAllHotels: "అన్ని హోటళ్లు చూడండి",
    guestReviews: "అతిథి సమీక్షలు",
    reviewsCount: "సమీక్షలు",
    noReviewsYet: "ఇంకా సమీక్షలు లేవు. మొదటివారు అవ్వండి!",
    writeAReview: "సమీక్ష రాయండి",
    loginToReview: "మీ అనుభవాన్ని పంచుకోవడానికి లాగిన్ అవ్వండి.",
    reviewPlaceholder: "మీ అనుభవాన్ని పంచుకోండి...",
    submitting: "సమర్పిస్తోంది...",
    submitReview: "సమీక్ష సమర్పించండి",
    backToHotels: "హోటళ్లకు తిరిగి వెళ్ళండి",
    night: "రాత్రి",
    aboutTheHotel: "హోటల్ గురించి",
    featuredAmenities: "ప్రత్యేక సౌకర్యాలు",
    allAmenities: "అన్ని సౌకర్యాలు",
    bestPriceGuaranteed: "ఉత్తమ ధర గ్యారంటీ",
    bookYourStay: "మీ స్టే బుక్ చేయండి",
    checkAvailability: "లభ్యత తనిఖీ చేయండి",
    freeCancellationHotel: "చెక్-ఇన్ కు 48 గంటల ముందు వరకు ఉచిత రద్దు",
    backToPackages: "ప్యాకేజీలకు తిరిగి వెళ్ళండి",
    packageDescription: "ప్యాకేజీ వివరణ",
    bestValue: "ఉత్తమ విలువ",
    perPackage: "మొత్తం",
    selectDepartureDate: "బయలుదేరే తేదీ ఎంచుకోండి",
    bookPackageNow: "ఈ ప్యాకేజీ బుక్ చేయండి",
    customizeItinerary: "యాత్ర ప్రణాళికను అనుకూలీకరించండి",
    priceIncludesTax: "ధరలో అన్ని పన్నులు ఉన్నాయి",
    insuranceIncluded: "ట్రావెల్ ఇన్సూరెన్స్ చేర్చబడింది",
    destinationNotFound: "గమ్యస్థానం కనుగొనబడలేదు",
    destinationNotFoundDesc: "మీరు వెతుకుతున్న గమ్యస్థానం ఉనికిలో లేదు.",
    errorInvalidCredentials: "చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్.",
    errorEmailNotConfirmed: "దయచేసి మీ ఇమెయిల్ చిరునామాను ధృవీకరించండి.",
    errorRateLimit: "చాలా ప్రయత్నాలు. దయచేసి తర్వాత మళ్ళీ ప్రయత్నించండి.",
    errorUnexpected: "ఎదురుచూడని లోపం సంభవించింది.",
    checkEmailConfirm: "మీ ఖాతాను ధృవీకరించడానికి దయచేసి మీ ఇమెయిల్ తనిఖీ చేయండి.",
  },
  kn: {
    home: "ಮುಖಪುಟ",
    destinations: "ತಲುಪುವಿಕೆಗಳು",
    hotels: "ಹೋಟೆಲ್‌ಗಳು",
    packages: "ಪ್ಯಾಕೇಜ್‌ಗಳು",
    contact: "ಸಂಪರ್ಕಿಸಿ",
    bookNow: "ಈಗಲೇ ಬುಕ್ ಮಾಡಿ",
    searchPlaceholder: "ನೀವು ಎಲ್ಲಿಗೆ ಹೋಗಲು ಬಯಸುತ್ತೀರಿ?",
    heroTitle: "ಪ್ರೀಮಿಯಂ ರೆಡ್ ವೆಲ್ವೆಟ್ ಪ್ರಯಾಣ",
    heroSubtitle: "ನಮ್ಮ ಕ್ಯುರೇಟೆಡ್ ಪ್ರಯಾಣ ಮಾರ್ಗದರ್ಶಿಗಳೊಂದಿಗೆ ಐಷಾರಾಮಿಯನ್ನು ಅನುಭವಿಸಿ.",
    viewDetails: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    exploreMore: "ಹೆಚ್ಚು ಅನ್ವೇಷಿಸಿ",
    contactAgent: "ಏಜೆಂಟ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    profile: "ಪ್ರೊಫೈಲ್",
    logout: "ಲಾಗ್ ಔಟ್",
    featuredDestinations: "ವೈಶಿಷ್ಟ್ಯಪೂರ್ಣ ತಲುಪುವಿಕೆಗಳು",
    popularCategories: "ಜನಪ್ರಿಯ ವರ್ಗಗಳು",
    luxuryStays: "ಐಷಾರಾಮಿ ತಂಗುವಿಕೆಗಳು",
    luxuryStaysDesc: "ಜಗತ್ತಿನ ಅತ್ಯಂತ ಪ್ರತಿಷ್ಠಿತ ಹೋಟೆಲ್‌ಗಳು ಮತ್ತು ರೆಸಾರ್ಟ್‌ಗಳ ಸಂಗ್ರಹ.",
    curatedTourPackages: "ಕ್ಯುರೇಟೆಡ್ ಟೂರ್ ಪ್ಯಾಕೇಜ್‌ಗಳು",
    curatedTourPackagesDesc: "ಐಷಾರಾಮಿ, ಸಾಹಸ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ಅತ್ಯುತ್ತಮ ಮಿಶ್ರಣ.",
    exclusiveOffers: "ವಿಶೇಷ ಆಫರ್‌ಗಳು",
    bookStay: "ತಂಗುವಿಕೆ ಬುಕ್ ಮಾಡಿ",
    perNight: "ಪ್ರತಿ ರಾತ್ರಿ",
    recommended: "ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ",
    allInclusive: "ಎಲ್ಲಾ ಸೇರಿದೆ",
    experienceIndia: "ಭಾರತವನ್ನು ಅನುಭವಿಸಿ",
    experiencePackages: "ಅನುಭವ ಪ್ಯಾಕೇಜ್‌ಗಳು",
    experiencePackagesDesc: "ಪ್ರತಿ ರೀತಿಯ ಪ್ರಯಾಣಿಕರಿಗೆ ಕ್ಯುರೇಟೆಡ್ ಪ್ರಯಾಣ ಅನುಭವಗಳು",
    exploreWorld: "ಜಗತ್ತನ್ನು ಅನ್ವೇಷಿಸಿ",
    popularDestinations: "ಜನಪ್ರಿಯ ತಲುಪುವಿಕೆಗಳು",
    popularDestinationsDesc: "ಜಗತ್ತಿನ ಅತ್ಯಂತ ಸುಂದರವಾದ ತಲುಪುವಿಕೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ",
    viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    footerDesc: "ಆಧುನಿಕ ಸಾಹಸಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಜಗತ್ತಿನ ಮೊದಲ ಪ್ರೀಮಿಯಂ ಪ್ರಯಾಣ ವೇದಿಕೆ. ಐಷಾರಾಮಿ, ಸರಳೀಕೃತ.",
    privacyPolicy: "ಗೌಪ್ಯತಾ ನೀತಿ",
    termsOfService: "ಸೇವಾ ನಿಯಮಗಳು",
    allRightsReserved: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    heritageAndCulture: "ಪರಂಪರೆ & ಸಂಸ್ಕೃತಿ",
    heritageAndCultureDesc: "ಪ್ರಾಚೀನ ದೇವಾಲಯಗಳು & ಸ್ಮಾರಕಗಳು",
    adventureAndThrills: "ಸಾಹಸ & ಥ್ರಿಲ್‌ಗಳು",
    adventureAndThrillsDesc: "ಟ್ರೆಕ್ಕಿಂಗ್ & ಎಕ್ಸ್ಟ್ರೀಮ್ ಸ್ಪೋರ್ಟ್ಸ್",
    wildlifeSafari: "ವನ್ಯಜೀವಿ ಸಫಾರಿ",
    wildlifeSafariDesc: "ರಾಷ್ಟ್ರೀಯ ಉದ್ಯಾನಗಳು & ಮೀಸಲುಗಳು",
    beachAndRelaxation: "ಬೀಚ್ & ವಿಶ್ರಾಂತಿ",
    beachAndRelaxationDesc: "ಕರಾವಳಿ ವಿಹಾರಗಳು",
    spiritualJourneys: "ಆಧ್ಯಾತ್ಮಿಕ ಪ್ರಯಾಣಗಳು",
    spiritualJourneysDesc: "ತೀರ್ಥಯಾತ್ರೆ & ಕ್ಷೇಮ",
    foodAndCulinary: "ಆಹಾರ & ಪಾಕಶಾಸ್ತ್ರ",
    foodAndCulinaryDesc: "ಸ್ಥಳೀಯ ಪಾಕಶೈಲಿ ಅನುಭವಗಳು",
    wifi: "ವೈಫೈ",
    breakfast: "ಉಪಾಹಾರ",
    pool: "ಈಜುಕೊಳ",
    dining: "ಭೋಜನಾಲಯ",
    speakWithSpecialist: "ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ",
    speakWithSpecialistDesc: "ನಮ್ಮ ಐಷಾರಾಮಿ ಪ್ರಯಾಣ ಏಜೆಂಟ್‌ಗಳು ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ರಜೆಯನ್ನು ರಚಿಸಲು ಸಿದ್ಧರಾಗಿದ್ದಾರೆ.",
    emailUs: "ಇಮೇಲ್ ಕಳುಹಿಸಿ",
    callAnytime: "ಕರೆ ಮಾಡಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    yourInquiry: "ನಿಮ್ಮ ವಿಚಾರಣೆ",
    inquiryPlaceholder: "ನಿಮ್ಮ ಕನಸಿನ ತಲುಪುವಿಕೆಯ ಬಗ್ಗೆ ಹೇಳಿ...",
    sendInquiry: "ವಿಚಾರಣೆ ಕಳುಹಿಸಿ",
    sending: "ಕಳುಹಿಸುತ್ತಿದೆ...",
    messageReceived: "ಸಂದೇಶ ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    messageReceivedDesc: "ನಮ್ಮ ತಜ್ಞರು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ.",
    sendAnotherMessage: "ಮತ್ತೊಂದು ಸಂದೇಶ ಕಳುಹಿಸಿ",
    confirmBooking: "ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ",
    travelDates: "ಪ್ರಯಾಣ ದಿನಾಂಕಗಳು",
    numberOfTravelers: "ಪ್ರಯಾಣಿಕರ ಸಂಖ್ಯೆ",
    paymentDetails: "ಪಾವತಿ ವಿವರಗಳು",
    cardholderName: "ಕಾರ್ಡ್ ಹೊಂದಿರುವವರ ಹೆಸರು",
    cardNumber: "ಕಾರ್ಡ್ ಸಂಖ್ಯೆ",
    processing: "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದೆ...",
    completeBooking: "ಬುಕಿಂಗ್ ಪೂರ್ಣಗೊಳಿಸಿ",
    baseFare: "ಮೂಲ ದರ",
    taxesFees: "ತೆರಿಗೆಗಳು & ಶುಲ್ಕಗಳು",
    total: "ಒಟ್ಟು",
    secureCheckout: "ಸುರಕ್ಷಿತ ಚೆಕ್‌ಔಟ್",
    welcome: "ಸ್ವಾಗತ",
    accountSettings: "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    memberBenefits: "ಸದಸ್ಯ ಪ್ರಯೋಜನಗಳು",
    premiumStatus: "ಪ್ರೀಮಿಯಂ ಸ್ಥಿತಿ",
    exclusiveOffersAvailable: "ವಿಶೇಷ ಆಫರ್‌ಗಳು ಲಭ್ಯವಿವೆ",
    travelCreditAvailable: "ಪ್ರಯಾಣ ಕ್ರೆಡಿಟ್ ಲಭ್ಯವಿದೆ",
    planNextTrip: "ಮುಂದಿನ ಪ್ರವಾಸವನ್ನು ಯೋಜಿಸಿ",
    planNextTripDesc: "ಚಳಿಗಾಲ 2024 ಕ್ಕಾಗಿ ನಮ್ಮ ಹೊಸ ತಲುಪುವಿಕೆಗಳನ್ನು ನೋಡಿ.",
    myBookings: "ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು",
    newBooking: "ಹೊಸ ಬುಕಿಂಗ್",
    viewDetailsBtn: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    noBookingsYet: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಪ್ರವಾಸವನ್ನು ಬುಕ್ ಮಾಡಿಲ್ಲ.",
    bookFirstTrip: "ನಿಮ್ಮ ಮೊದಲ ಪ್ರವಾಸವನ್ನು ಬುಕ್ ಮಾಡಿ",
    aboutJourney: "ಈ ಪ್ರಯಾಣದ ಬಗ್ಗೆ",
    journeyHighlights: "ಪ್ರಯಾಣದ ಮುಖ್ಯಾಂಶಗಳು",
    whatsIncluded: "ಏನು ಸೇರಿದೆ",
    premiumPackage: "ಪ್ರೀಮಿಯಂ ಪ್ಯಾಕೇಜ್",
    selectDate: "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    travelers: "ಪ್ರಯಾಣಿಕರು",
    basePrice: "ಮೂಲ ಬೆಲೆ",
    serviceFee: "ಸೇವಾ ಶುಲ್ಕ",
    bookTripNow: "ಈಗ ಪ್ರವಾಸ ಬುಕ್ ಮಾಡಿ",
    freeCancellation: "ಪ್ರವಾಸಕ್ಕೆ 48 ಗಂಟೆ ಮೊದಲು ಉಚಿತ ರದ್ದತಿ.",
    backToDestinations: "ತಲುಪುವಿಕೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    enterCredentials: "ನಿಮ್ಮ ಐಷಾರಾಮಿ ಪ್ರವಾಸಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ರುಜುವಾತುಗಳನ್ನು ನಮೂದಿಸಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    signIn: "ಸೈನ್ ಇನ್",
    signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...",
    noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    joinUs: "ವಿಶೇಷ ಐಷಾರಾಮಿ ಪ್ರಯಾಣ ಅನುಭವಗಳಿಗಾಗಿ Orchids Travel ಗೆ ಸೇರಿ",
    creatingAccount: "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    flights: "ವಿಮಾನಗಳು",
    flightsDesc: "ಅಂತಾರಾಷ್ಟ್ರೀಯ ಮತ್ತು ದೇಶೀಯ ವಿಮಾನಗಳಲ್ಲಿ ಅತ್ಯುತ್ತಮ ಡೀಲ್‌ಗಳು.",
    tours: "ಟೂರ್‌ಗಳು",
    toursDesc: "ಕುಟುಂಬಗಳಿಗೆ ಆಲ್-ಇನ್‌ಕ್ಲೂಸಿವ್ ರಜಾದಿನ ಪ್ಯಾಕೇಜ್‌ಗಳು.",
    readyForAdventure: "ನಿಮ್ಮ ಮುಂದಿನ ಸಾಹಸಕ್ಕೆ ಸಿದ್ಧರಿದ್ದೀರಾ?",
    readyForAdventureDesc: "Orchids Travel ನೊಂದಿಗೆ ಕನಸಿನ ರಜೆಯನ್ನು ಕಂಡುಕೊಂಡ ಸಾವಿರಾರು ಪ್ರಯಾಣಿಕರೊಂದಿಗೆ ಸೇರಿ.",
    exploreFooter: "ಅನ್ವೇಷಿಸಿ",
    contactFooter: "ಸಂಪರ್ಕ",
    addDates: "ದಿನಾಂಕಗಳನ್ನು ಸೇರಿಸಿ",
    search: "ಹುಡುಕಿ",
    noDestinationsFound: "ತಲುಪುವಿಕೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    noDestinationsFoundDesc: "ನಿಮ್ಮ ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ.",
    clearAllFilters: "ಎಲ್ಲಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ",
    startingFrom: "ಇಂದ",
    all: "ಎಲ್ಲಾ",
    romantic: "ರೊಮ್ಯಾಂಟಿಕ್",
    adventure: "ಸಾಹಸ",
    cultural: "ಸಾಂಸ್ಕೃತಿಕ",
    tropical: "ಉಷ್ಣವಲಯ",
    luxury: "ಐಷಾರಾಮಿ",
    viewAllPackages: "ಎಲ್ಲಾ ಪ್ಯಾಕೇಜ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    viewAllHotels: "ಎಲ್ಲಾ ಹೋಟೆಲ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    guestReviews: "ಅತಿಥಿ ವಿಮರ್ಶೆಗಳು",
    reviewsCount: "ವಿಮರ್ಶೆಗಳು",
    noReviewsYet: "ಇನ್ನೂ ವಿಮರ್ಶೆಗಳಿಲ್ಲ. ಮೊದಲಿಗರಾಗಿ!",
    writeAReview: "ವಿಮರ್ಶೆ ಬರೆಯಿರಿ",
    loginToReview: "ನಿಮ್ಮ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ಲಾಗಿನ್ ಆಗಿ.",
    reviewPlaceholder: "ನಿಮ್ಮ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...",
    submitting: "ಸಲ್ಲಿಸುತ್ತಿದೆ...",
    submitReview: "ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ",
    backToHotels: "ಹೋಟೆಲ್‌ಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    night: "ರಾತ್ರಿ",
    aboutTheHotel: "ಹೋಟೆಲ್ ಬಗ್ಗೆ",
    featuredAmenities: "ವಿಶೇಷ ಸೌಲಭ್ಯಗಳು",
    allAmenities: "ಎಲ್ಲಾ ಸೌಲಭ್ಯಗಳು",
    bestPriceGuaranteed: "ಅತ್ಯುತ್ತಮ ಬೆಲೆ ಖಾತರಿ",
    bookYourStay: "ನಿಮ್ಮ ತಂಗುವಿಕೆಯನ್ನು ಬುಕ್ ಮಾಡಿ",
    checkAvailability: "ಲಭ್ಯತೆ ಪರಿಶೀಲಿಸಿ",
    freeCancellationHotel: "ಚೆಕ್-ಇನ್ ಗೆ 48 ಗಂಟೆ ಮೊದಲು ಉಚಿತ ರದ್ದತಿ",
    backToPackages: "ಪ್ಯಾಕೇಜ್‌ಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    packageDescription: "ಪ್ಯಾಕೇಜ್ ವಿವರಣೆ",
    bestValue: "ಅತ್ಯುತ್ತಮ ಮೌಲ್ಯ",
    perPackage: "ಒಟ್ಟು",
    selectDepartureDate: "ಹೊರಡುವ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    bookPackageNow: "ಈ ಪ್ಯಾಕೇಜ್ ಬುಕ್ ಮಾಡಿ",
    customizeItinerary: "ಪ್ರವಾಸ ಯೋಜನೆಯನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ",
    priceIncludesTax: "ಬೆಲೆಯಲ್ಲಿ ಎಲ್ಲಾ ತೆರಿಗೆಗಳು ಸೇರಿವೆ",
    insuranceIncluded: "ಪ್ರಯಾಣ ವಿಮೆ ಸೇರಿದೆ",
    destinationNotFound: "ಗಮ್ಯಸ್ಥಾನ ಕಂಡುಬಂದಿಲ್ಲ",
    destinationNotFoundDesc: "ನೀವು ಹುಡುಕುತ್ತಿರುವ ಗಮ್ಯಸ್ಥಾನ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ.",
    errorInvalidCredentials: "ಅಮಾನ್ಯ ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್.",
    errorEmailNotConfirmed: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ದೃಢೀಕರಿಸಿ.",
    errorRateLimit: "ಹೆಚ್ಚಿನ ಪ್ರಯತ್ನಗಳು. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    errorUnexpected: "ಅನಿರೀಕ್ಷಿತ ದೋಷ ಸಂಭವಿಸಿದೆ.",
    checkEmailConfirm: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ದೃಢೀಕರಿಸಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ.",
  },
  ml: {
    home: "ഹോം",
    destinations: "ലക്ഷ്യസ്ഥാനങ്ങൾ",
    hotels: "ഹോട്ടലുകൾ",
    packages: "പാക്കേജുകൾ",
    contact: "ബന്ധപ്പെടുക",
    bookNow: "ഇപ്പോൾ ബുക്ക് ചെയ്യുക",
    searchPlaceholder: "നിങ്ങൾ എവിടേക്ക് പോകാൻ ആഗ്രഹിക്കുന്നു?",
    heroTitle: "പ്രീമിയം റെഡ് വെൽവെറ്റ് ട്രാവൽ",
    heroSubtitle: "ഞങ്ങളുടെ ക്യൂറേറ്റഡ് ട്രാവൽ ഗൈഡുകളിലൂടെ ആഡംബരം അനുഭവിക്കുക.",
    viewDetails: "വിശദാംശങ്ങൾ കാണുക",
    exploreMore: "കൂടുതൽ പര്യവേക്ഷണം ചെയ്യുക",
    contactAgent: "ഏജന്റിനെ ബന്ധപ്പെടുക",
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്പ്",
    profile: "പ്രൊഫൈൽ",
    logout: "ലോഗ് ഔട്ട്",
    featuredDestinations: "ഫീച്ചർ ചെയ്ത ലക്ഷ്യസ്ഥാനങ്ങൾ",
    popularCategories: "ജനപ്രിയ വിഭാഗങ്ങൾ",
    luxuryStays: "ആഡംബര താമസം",
    luxuryStaysDesc: "ലോകത്തിലെ ഏറ്റവും പ്രശസ്തമായ ഹോട്ടലുകളുടെയും റിസോർട്ടുകളുടെയും ശേഖരം.",
    curatedTourPackages: "ക്യൂറേറ്റഡ് ടൂർ പാക്കേജുകൾ",
    curatedTourPackagesDesc: "ആഡംബരം, സാഹസികത, സംസ്കാരം എന്നിവയുടെ മികച്ച മിശ്രിതം.",
    exclusiveOffers: "പ്രത്യേക ഓഫറുകൾ",
    bookStay: "താമസം ബുക്ക് ചെയ്യുക",
    perNight: "ഒരു രാത്രിക്ക്",
    recommended: "ശുപാർശ ചെയ്യുന്നു",
    allInclusive: "എല്ലാം ഉൾപ്പെടുന്നു",
    experienceIndia: "ഇന്ത്യ അനുഭവിക്കുക",
    experiencePackages: "അനുഭവ പാക്കേജുകൾ",
    experiencePackagesDesc: "എല്ലാ തരം യാത്രക്കാർക്കുമുള്ള ക്യൂറേറ്റഡ് യാത്രാ അനുഭവങ്ങൾ",
    exploreWorld: "ലോകം പര്യവേക്ഷണം ചെയ്യുക",
    popularDestinations: "ജനപ്രിയ ലക്ഷ്യസ്ഥാനങ്ങൾ",
    popularDestinationsDesc: "ലോകത്തിലെ ഏറ്റവും മനോഹരമായ ലക്ഷ്യസ്ഥാനങ്ങൾ കണ്ടെത്തുക",
    viewAll: "എല്ലാം കാണുക",
    footerDesc: "ആധുനിക സാഹസികർക്കായി രൂപകൽപ്പന ചെയ്ത ലോകത്തിലെ ആദ്യത്തെ പ്രീമിയം ട്രാവൽ പ്ലാറ്റ്‌ഫോം. ആഡംബരം, ലളിതമാക്കി.",
    privacyPolicy: "സ്വകാര്യതാ നയം",
    termsOfService: "സേവന നിബന്ധനകൾ",
    allRightsReserved: "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.",
    heritageAndCulture: "പൈതൃകവും സംസ്കാരവും",
    heritageAndCultureDesc: "പുരാതന ക്ഷേത്രങ്ങളും സ്മാരകങ്ങളും",
    adventureAndThrills: "സാഹസികതയും ത്രില്ലും",
    adventureAndThrillsDesc: "ട്രെക്കിംഗും എക്സ്ട്രീം സ്പോർട്സും",
    wildlifeSafari: "വന്യജീവി സഫാരി",
    wildlifeSafariDesc: "ദേശീയ ഉദ്യാനങ്ങളും സംരക്ഷണ കേന്ദ്രങ്ങളും",
    beachAndRelaxation: "ബീച്ചും വിശ്രമവും",
    beachAndRelaxationDesc: "തീരദേശ ഒഴിവുകാലം",
    spiritualJourneys: "ആത്മീയ യാത്രകൾ",
    spiritualJourneysDesc: "തീർത്ഥാടനവും ക്ഷേമവും",
    foodAndCulinary: "ഭക്ഷണവും പാചകവും",
    foodAndCulinaryDesc: "പ്രാദേശിക പാചക അനുഭവങ്ങൾ",
    wifi: "വൈഫൈ",
    breakfast: "പ്രഭാതഭക്ഷണം",
    pool: "നീന്തൽക്കുളം",
    dining: "ഭക്ഷണശാല",
    speakWithSpecialist: "വിദഗ്ധനുമായി സംസാരിക്കുക",
    speakWithSpecialistDesc: "നിങ്ങളുടെ മികച്ച അവധിക്കാലം സൃഷ്ടിക്കാൻ ഞങ്ങളുടെ ആഡംബര ട്രാവൽ ഏജന്റുമാർ തയ്യാറാണ്.",
    emailUs: "ഇമെയിൽ അയയ്ക്കുക",
    callAnytime: "കോൾ ചെയ്യുക",
    fullName: "മുഴുവൻ പേര്",
    emailAddress: "ഇമെയിൽ വിലാസം",
    yourInquiry: "നിങ്ങളുടെ അന്വേഷണം",
    inquiryPlaceholder: "നിങ്ങളുടെ സ്വപ്ന ലക്ഷ്യസ്ഥാനത്തെക്കുറിച്ച് പറയൂ...",
    sendInquiry: "അന്വേഷണം അയയ്ക്കുക",
    sending: "അയയ്ക്കുന്നു...",
    messageReceived: "സന്ദേശം ലഭിച്ചു",
    messageReceivedDesc: "ഞങ്ങളുടെ വിദഗ്ധർ ഉടൻ നിങ്ങളെ ബന്ധപ്പെടും.",
    sendAnotherMessage: "മറ്റൊരു സന്ദേശം അയയ്ക്കുക",
    confirmBooking: "ബുക്കിംഗ് സ്ഥിരീകരിക്കും",
    travelDates: "യാത്രാ തീയതികൾ",
    numberOfTravelers: "യാത്രക്കാരുടെ എണ്ണം",
    paymentDetails: "പേയ്‌മെന്റ് വിശദാംശങ്ങൾ",
    cardholderName: "കാർഡ് ഉടമയുടെ പേര്",
    cardNumber: "കാർഡ് നമ്പർ",
    processing: "പ്രോസസ്സ് ചെയ്യുന്നു...",
    completeBooking: "ബുക്കിംഗ് പൂർത്തിയാക്കുക",
    baseFare: "അടിസ്ഥാന നിരക്ക്",
    taxesFees: "നികുതികൾ & ഫീസുകൾ",
    total: "ആകെ",
    secureCheckout: "സുരക്ഷിത ചെക്ക്ഔട്ട്",
    welcome: "സ്വാഗതം",
    accountSettings: "അക്കൗണ്ട് ക്രമീകരണങ്ങൾ",
    memberBenefits: "അംഗ ആനുകൂല്യങ്ങൾ",
    premiumStatus: "പ്രീമിയം നില",
    exclusiveOffersAvailable: "പ്രത്യേക ഓഫറുകൾ ലഭ്യമാണ്",
    travelCreditAvailable: "ട്രാവൽ ക്രെഡിറ്റ് ലഭ്യമാണ്",
    planNextTrip: "അടുത്ത യാത്ര ആസൂത്രണം ചെയ്യുക",
    planNextTripDesc: "ശൈത്യകാലം 2024-ലേക്കുള്ള ഞങ്ങളുടെ പുതിയ ലക്ഷ്യസ്ഥാനങ്ങൾ കാണുക.",
    myBookings: "എന്റെ ബുക്കിംഗുകൾ",
    newBooking: "പുതിയ ബുക്കിംഗ്",
    viewDetailsBtn: "വിശദാംശങ്ങൾ കാണുക",
    noBookingsYet: "നിങ്ങൾ ഇതുവരെ യാത്രകളൊന്നും ബുക്ക് ചെയ്തിട്ടില്ല.",
    bookFirstTrip: "നിങ്ങളുടെ ആദ്യ യാത്ര ബുക്ക് ചെയ്യുക",
    aboutJourney: "ഈ യാത്രയെക്കുറിച്ച്",
    journeyHighlights: "യാത്രാ ഹൈലൈറ്റുകൾ",
    whatsIncluded: "എന്തെല്ലാം ഉൾപ്പെടുന്നു",
    premiumPackage: "പ്രീമിയം പാക്കേജ്",
    selectDate: "തീയതി തിരഞ്ഞെടുക്കുക",
    travelers: "യാത്രക്കാർ",
    basePrice: "അടിസ്ഥാന വില",
    serviceFee: "സർവീസ് ഫീസ്",
    bookTripNow: "ഇപ്പോൾ യാത്ര ബുക്ക് ചെയ്യുക",
    freeCancellation: "യാത്രയ്ക്ക് 48 മണിക്കൂർ മുമ്പ് വരെ സൗജന്യ റദ്ദാക്കൽ.",
    backToDestinations: "ലക്ഷ്യസ്ഥാനങ്ങളിലേക്ക് മടങ്ങുക",
    welcomeBack: "തിരികെ സ്വാഗതം",
    enterCredentials: "നിങ്ങളുടെ ആഡംബര യാത്രകൾ ആക്‌സസ് ചെയ്യാൻ ക്രെഡൻഷ്യലുകൾ നൽകുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
    signIn: "സൈൻ ഇൻ",
    signingIn: "സൈൻ ഇൻ ചെയ്യുന്നു...",
    noAccount: "അക്കൗണ്ട് ഇല്ലേ?",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    joinUs: "പ്രത്യേക ആഡംബര യാത്രാ അനുഭവങ്ങൾക്കായി Orchids Travel-ൽ ചേരുക",
    creatingAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    flights: "വിമാനങ്ങൾ",
    flightsDesc: "അന്തർദേശീയ, ആഭ്യന്തര വിമാനങ്ങളിൽ മികച്ച ഡീലുകൾ.",
    tours: "ടൂറുകൾ",
    toursDesc: "കുടുംബങ്ങൾക്കുള്ള ഓൾ-ഇൻക്ലൂസീവ് വേക്കേഷൻ പാക്കേജുകൾ.",
    readyForAdventure: "നിങ്ങളുടെ അടുത്ത സാഹസികതയ്ക്ക് തയ്യാറാണോ?",
    readyForAdventureDesc: "Orchids Travel-ലൂടെ സ്വപ്ന അവധിക്കാലം കണ്ടെത്തിയ ആയിരക്കണക്കിന് യാത്രക്കാരോടൊപ്പം ചേരുക.",
    exploreFooter: "പര്യവേക്ഷണം ചെയ്യുക",
    contactFooter: "ബന്ധപ്പെടുക",
    addDates: "തീയതികൾ ചേർക്കുക",
    search: "തിരയുക",
    noDestinationsFound: "ലക്ഷ്യസ്ഥാനങ്ങൾ കണ്ടെത്തിയില്ല",
    noDestinationsFoundDesc: "നിങ്ങളുടെ തിരയൽ അല്ലെങ്കിൽ ഫിൽട്ടറുകൾ ക്രമീകരിക്കാൻ ശ്രമിക്കുക.",
    clearAllFilters: "എല്ലാ ഫിൽട്ടറുകളും മായ്ക്കുക",
    startingFrom: "മുതൽ",
    all: "എല്ലാം",
    romantic: "റൊമാന്റിക്",
    adventure: "സാഹസികം",
    cultural: "സാംസ്കാരികം",
    tropical: "ഉഷ്ണമേഖല",
    luxury: "ആഡംബരം",
    viewAllPackages: "എല്ലാ പാക്കേജുകളും കാണുക",
    viewAllHotels: "എല്ലാ ഹോട്ടലുകളും കാണുക",
    guestReviews: "അതിഥി അവലോകനങ്ങൾ",
    reviewsCount: "അവലോകനങ്ങൾ",
    noReviewsYet: "ഇതുവരെ അവലോകനങ്ങളില്ല. ആദ്യത്തെയാളാകുക!",
    writeAReview: "അവലോകനം എഴുതുക",
    loginToReview: "നിങ്ങളുടെ അനുഭവം പങ്കിടാൻ ലോഗിൻ ചെയ്യുക.",
    reviewPlaceholder: "നിങ്ങളുടെ അനുഭവം പങ്കിടുക...",
    submitting: "സമർപ്പിക്കുന്നു...",
    submitReview: "അവലോകനം സമർപ്പിക്കുക",
    backToHotels: "ഹോട്ടലുകളിലേക്ക് മടങ്ങുക",
    night: "രാത്രി",
    aboutTheHotel: "ഹോട്ടലിനെക്കുറിച്ച്",
    featuredAmenities: "പ്രത്യേക സൗകര്യങ്ങൾ",
    allAmenities: "എല്ലാ സൗകര്യങ്ങളും",
    bestPriceGuaranteed: "മികച്ച വില ഗ്യാരണ്ടി",
    bookYourStay: "നിങ്ങളുടെ താമസം ബുക്ക് ചെയ്യുക",
    checkAvailability: "ലഭ്യത പരിശോധിക്കുക",
    freeCancellationHotel: "ചെക്ക്-ഇന് 48 മണിക്കൂർ മുമ്പ് വരെ സൗജന്യ റദ്ദാക്കൽ",
    backToPackages: "പാക്കേജുകളിലേക്ക് മടങ്ങുക",
    packageDescription: "പാക്കേജ് വിവരണം",
    bestValue: "മികച്ച മൂല്യം",
    perPackage: "ആകെ",
    selectDepartureDate: "പുറപ്പെടൽ തീയതി തിരഞ്ഞെടുക്കുക",
    bookPackageNow: "ഈ പാക്കേജ് ബുക്ക് ചെയ്യുക",
    customizeItinerary: "യാത്രാ പദ്ധതി ഇഷ്ടാനുസൃതമാക്കുക",
    priceIncludesTax: "വിലയിൽ എല്ലാ നികുതികളും ഉൾപ്പെടുന്നു",
    insuranceIncluded: "ട്രാവൽ ഇൻഷുറൻസ് ഉൾപ്പെടുന്നു",
    destinationNotFound: "ലക്ഷ്യസ്ഥാനം കണ്ടെത്തിയില്ല",
    destinationNotFoundDesc: "നിങ്ങൾ തിരയുന്ന ലക്ഷ്യസ്ഥാനം നിലവിലില്ല.",
    errorInvalidCredentials: "അസാധുവായ ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ്.",
    errorEmailNotConfirmed: "നിങ്ങളുടെ ഇമെയിൽ വിലാസം സ്ഥിരീകരിക്കുക.",
    errorRateLimit: "അമിതമായ ശ്രമങ്ങൾ. പിന്നീട് വീണ്ടും ശ്രമിക്കുക.",
    errorUnexpected: "അപ്രതീക്ഷിതമായ ഒരു പിശക് സംഭവിച്ചു.",
    checkEmailConfirm: "നിങ്ങളുടെ അക്കൗണ്ട് സ്ഥിരീകരിക്കുന്നതിന് ദയവായി നിങ്ങളുടെ ഇമെയിൽ പരിശോധിക്കുക.",
  },
  zh: {
    home: "首页",
    destinations: "目的地",
    hotels: "酒店",
    packages: "套餐",
    contact: "联系我们",
    bookNow: "立即预订",
    searchPlaceholder: "您想去哪里？",
    heroTitle: "尊享红丝绒旅行",
    heroSubtitle: "通过我们精心策划的旅行指南，体验前所未有的奢华。",
    viewDetails: "查看详情",
    exploreMore: "探索更多",
    contactAgent: "联系代理",
    login: "登录",
    signup: "注册",
    profile: "个人资料",
    logout: "退出登录",
    featuredDestinations: "精选目的地",
    popularCategories: "热门类别",
    luxuryStays: "奢华住宿",
    luxuryStaysDesc: "精选全球最负盛名的酒店和度假村。",
    curatedTourPackages: "精选旅游套餐",
    curatedTourPackagesDesc: "融合奢华、冒险与文化的精心定制行程。",
    exclusiveOffers: "独家优惠",
    bookStay: "预订住宿",
    perNight: "每晚",
    recommended: "推荐",
    allInclusive: "全包价",
    experienceIndia: "体验印度",
    experiencePackages: "体验套餐",
    experiencePackagesDesc: "为每种类型的旅行者精选的旅行体验",
    exploreWorld: "探索世界",
    popularDestinations: "热门目的地",
    popularDestinationsDesc: "发现世界上最令人叹为观止的目的地",
    viewAll: "查看全部",
    footerDesc: "为现代冒险家设计的世界首个高端旅行平台。奢华，简化。",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    allRightsReserved: "保留所有权利。",
    heritageAndCulture: "遗产与文化",
    heritageAndCultureDesc: "古老寺庙和纪念碑",
    adventureAndThrills: "冒险与刺激",
    adventureAndThrillsDesc: "徒步旅行和极限运动",
    wildlifeSafari: "野生动物之旅",
    wildlifeSafariDesc: "国家公园和保护区",
    beachAndRelaxation: "海滩与休闲",
    beachAndRelaxationDesc: "海滨度假",
    spiritualJourneys: "心灵之旅",
    spiritualJourneysDesc: "朝圣和养生",
    foodAndCulinary: "美食与烹饪",
    foodAndCulinaryDesc: "当地美食体验",
    wifi: "无线网络",
    breakfast: "早餐",
    pool: "游泳池",
    dining: "餐厅",
    speakWithSpecialist: "与专家交谈",
    speakWithSpecialistDesc: "我们的奢华旅行代理随时为您打造完美假期。",
    emailUs: "发送邮件",
    callAnytime: "随时致电",
    fullName: "全名",
    emailAddress: "电子邮箱",
    yourInquiry: "您的咨询",
    inquiryPlaceholder: "告诉我们您的梦想目的地...",
    sendInquiry: "发送咨询",
    sending: "发送中...",
    messageReceived: "消息已收到",
    messageReceivedDesc: "我们的专家将尽快与您联系。",
    sendAnotherMessage: "发送另一条消息",
    confirmBooking: "确认预订",
    travelDates: "出行日期",
    numberOfTravelers: "旅客人数",
    paymentDetails: "支付详情",
    cardholderName: "持卡人姓名",
    cardNumber: "卡号",
    processing: "处理中...",
    completeBooking: "完成预订",
    baseFare: "基础票价",
    taxesFees: "税费",
    total: "总计",
    secureCheckout: "安全结账",
    welcome: "欢迎",
    accountSettings: "账户设置",
    memberBenefits: "会员权益",
    premiumStatus: "高级会员",
    exclusiveOffersAvailable: "独家优惠可用",
    travelCreditAvailable: "旅行积分可用",
    planNextTrip: "规划下一次旅行",
    planNextTripDesc: "探索我们2024年冬季新增的目的地。",
    myBookings: "我的预订",
    newBooking: "新预订",
    viewDetailsBtn: "查看详情",
    noBookingsYet: "您还没有预订任何行程。",
    bookFirstTrip: "预订您的第一次旅行",
    aboutJourney: "关于此行程",
    journeyHighlights: "行程亮点",
    whatsIncluded: "包含内容",
    premiumPackage: "高级套餐",
    selectDate: "选择日期",
    travelers: "旅客",
    basePrice: "基础价格",
    serviceFee: "服务费",
    bookTripNow: "立即预订行程",
    freeCancellation: "出发前48小时可免费取消。",
    backToDestinations: "返回目的地",
    welcomeBack: "欢迎回来",
    enterCredentials: "输入您的凭证以访问您的奢华旅行",
    email: "邮箱",
    password: "密码",
    forgotPassword: "忘记密码？",
    signIn: "登录",
    signingIn: "登录中...",
    noAccount: "没有账户？",
    createAccount: "创建账户",
    joinUs: "加入Orchids Travel，享受独家奢华旅行体验",
    creatingAccount: "创建账户中...",
    alreadyHaveAccount: "已有账户？",
    flights: "航班",
    flightsDesc: "国际和国内航班的最佳优惠。",
    tours: "旅游",
    toursDesc: "全包式家庭度假套餐。",
    readyForAdventure: "准备好您的下一次冒险了吗？",
    readyForAdventureDesc: "加入成千上万通过Orchids Travel找到梦想假期的旅行者。获得独家优惠和个性化行程。",
    exploreFooter: "探索",
    contactFooter: "联系",
    addDates: "添加日期",
    search: "搜索",
    noDestinationsFound: "未找到目的地",
    noDestinationsFoundDesc: "请尝试调整您的搜索或筛选条件。",
    clearAllFilters: "清除所有筛选",
    startingFrom: "起价",
    all: "全部",
    romantic: "浪漫",
    adventure: "冒险",
    cultural: "文化",
    tropical: "热带",
    luxury: "奢华",
    viewAllPackages: "查看所有套餐",
    viewAllHotels: "查看所有酒店",
    guestReviews: "客人评价",
    reviewsCount: "条评价",
    noReviewsYet: "暂无评价。成为第一个！",
    writeAReview: "撰写评价",
    loginToReview: "请登录以分享您的体验。",
    reviewPlaceholder: "分享您的体验...",
    submitting: "提交中...",
    submitReview: "提交评价",
    backToHotels: "返回酒店",
    night: "晚",
    aboutTheHotel: "关于酒店",
    featuredAmenities: "特色设施",
    allAmenities: "所有设施",
    bestPriceGuaranteed: "最优价格保证",
    bookYourStay: "预订住宿",
    checkAvailability: "查询空房",
    freeCancellationHotel: "入住前48小时可免费取消",
    backToPackages: "返回套餐",
    packageDescription: "套餐描述",
    bestValue: "超值优选",
    perPackage: "总价",
    selectDepartureDate: "选择出发日期",
    bookPackageNow: "预订此套餐",
    customizeItinerary: "定制行程",
    priceIncludesTax: "价格包含所有税费",
    insuranceIncluded: "含旅行保险",
    destinationNotFound: "未找到目的地",
    destinationNotFoundDesc: "您查找的目的地不存在。",
    errorInvalidCredentials: "邮箱或密码错误。",
    errorEmailNotConfirmed: "请确认您的电子邮箱地址。",
    errorRateLimit: "尝试次数过多，请稍后再试。",
    errorUnexpected: "发生了意外错误。",
    checkEmailConfirm: "请检查您的电子邮箱以确认您的账户。",
  },
  ja: {
    home: "ホーム",
    destinations: "目的地",
    hotels: "ホテル",
    packages: "パッケージ",
    contact: "お問い合わせ",
    bookNow: "今すぐ予約",
    searchPlaceholder: "どこに行きたいですか？",
    heroTitle: "プレミアムレッドベルベットトラベル",
    heroSubtitle: "厳選されたトラベルガイドで、かつてない贅沢を体験してください。",
    viewDetails: "詳細を見る",
    exploreMore: "もっと探索",
    contactAgent: "エージェントに連絡",
    login: "ログイン",
    signup: "サインアップ",
    profile: "プロフィール",
    logout: "ログアウト",
    featuredDestinations: "注目の目的地",
    popularCategories: "人気カテゴリ",
    luxuryStays: "ラグジュアリーステイ",
    luxuryStaysDesc: "世界で最も名高いホテルとリゾートの厳選コレクション。",
    curatedTourPackages: "厳選ツアーパッケージ",
    curatedTourPackagesDesc: "贅沢、冒険、文化を融合させた手作りの旅程。",
    exclusiveOffers: "限定オファー",
    bookStay: "宿泊を予約",
    perNight: "1泊",
    recommended: "おすすめ",
    allInclusive: "オールインクルーシブ",
    experienceIndia: "インドを体験",
    experiencePackages: "体験パッケージ",
    experiencePackagesDesc: "あらゆるタイプの旅行者のための厳選された旅行体験",
    exploreWorld: "世界を探検",
    popularDestinations: "人気の目的地",
    popularDestinationsDesc: "世界で最も息をのむような目的地を発見",
    viewAll: "すべて表示",
    footerDesc: "現代の冒険家のために設計された世界初のプレミアムトラベルプラットフォーム。贅沢、シンプルに。",
    privacyPolicy: "プライバシーポリシー",
    termsOfService: "利用規約",
    allRightsReserved: "無断複写・転載を禁じます。",
    heritageAndCulture: "遺産と文化",
    heritageAndCultureDesc: "古代寺院と記念碑",
    adventureAndThrills: "アドベンチャーとスリル",
    adventureAndThrillsDesc: "トレッキングとエクストリームスポーツ",
    wildlifeSafari: "野生動物サファリ",
    wildlifeSafariDesc: "国立公園と保護区",
    beachAndRelaxation: "ビーチとリラクゼーション",
    beachAndRelaxationDesc: "海辺の休暇",
    spiritualJourneys: "スピリチュアルな旅",
    spiritualJourneysDesc: "巡礼とウェルネス",
    foodAndCulinary: "食と料理",
    foodAndCulinaryDesc: "地元の料理体験",
    wifi: "Wi-Fi",
    breakfast: "朝食",
    pool: "プール",
    dining: "ダイニング",
    speakWithSpecialist: "スペシャリストと話す",
    speakWithSpecialistDesc: "当社のラグジュアリートラベルエージェントが完璧な休暇をお届けします。",
    emailUs: "メールする",
    callAnytime: "お電話",
    fullName: "氏名",
    emailAddress: "メールアドレス",
    yourInquiry: "お問い合わせ内容",
    inquiryPlaceholder: "夢の目的地についてお聞かせください...",
    sendInquiry: "お問い合わせを送信",
    sending: "送信中...",
    messageReceived: "メッセージを受信しました",
    messageReceivedDesc: "スペシャリストが近々ご連絡いたします。",
    sendAnotherMessage: "別のメッセージを送信",
    confirmBooking: "予約を確認",
    travelDates: "旅行日程",
    numberOfTravelers: "旅行者数",
    paymentDetails: "支払い詳細",
    cardholderName: "カード名義人",
    cardNumber: "カード番号",
    processing: "処理中...",
    completeBooking: "予約を完了",
    baseFare: "基本料金",
    taxesFees: "税金と手数料",
    total: "合計",
    secureCheckout: "安全なチェックアウト",
    welcome: "ようこそ",
    accountSettings: "アカウント設定",
    memberBenefits: "会員特典",
    premiumStatus: "プレミアムステータス",
    exclusiveOffersAvailable: "限定オファーあり",
    travelCreditAvailable: "旅行クレジットあり",
    planNextTrip: "次の旅行を計画",
    planNextTripDesc: "2024年冬の新しい目的地をご覧ください。",
    myBookings: "マイ予約",
    newBooking: "新規予約",
    viewDetailsBtn: "詳細を見る",
    noBookingsYet: "まだ旅行を予約していません。",
    bookFirstTrip: "最初の旅行を予約",
    aboutJourney: "この旅について",
    journeyHighlights: "旅のハイライト",
    whatsIncluded: "含まれるもの",
    premiumPackage: "プレミアムパッケージ",
    selectDate: "日付を選択",
    travelers: "旅行者",
    basePrice: "基本価格",
    serviceFee: "サービス料",
    bookTripNow: "今すぐ旅行を予約",
    freeCancellation: "出発48時間前まで無料キャンセル可能。",
    backToDestinations: "目的地に戻る",
    welcomeBack: "おかえりなさい",
    enterCredentials: "資格情報を入力してラグジュアリー旅行にアクセス",
    email: "メール",
    password: "パスワード",
    forgotPassword: "パスワードを忘れた？",
    signIn: "サインイン",
    signingIn: "サインイン中...",
    noAccount: "アカウントがない？",
    createAccount: "アカウント作成",
    joinUs: "Orchids Travelに参加して限定ラグジュアリー旅行体験を",
    creatingAccount: "アカウント作成中...",
    alreadyHaveAccount: "すでにアカウントをお持ち？",
    flights: "フライト",
    flightsDesc: "国際線・国内線の最安値。",
    tours: "ツアー",
    toursDesc: "ファミリー向けオールインクルーシブパッケージ。",
    readyForAdventure: "次の冒険の準備はできましたか？",
    readyForAdventureDesc: "Orchids Travelで夢の休暇を見つけた何千もの旅行者に参加してください。",
    exploreFooter: "探索",
    contactFooter: "連絡先",
    addDates: "日程を追加",
    search: "検索",
    noDestinationsFound: "目的地が見つかりません",
    noDestinationsFoundDesc: "検索またはフィルターを調整してみてください。",
    clearAllFilters: "すべてのフィルターをクリア",
    startingFrom: "から",
    all: "すべて",
    romantic: "ロマンチック",
    adventure: "アドベンチャー",
    cultural: "文化",
    tropical: "トロピカル",
    luxury: "ラグジュアリー",
    viewAllPackages: "すべてのパッケージを見る",
    viewAllHotels: "すべてのホテルを見る",
    guestReviews: "ゲストレビュー",
    reviewsCount: "件のレビュー",
    noReviewsYet: "まだレビューがありません。最初のレビューを！",
    writeAReview: "レビューを書く",
    loginToReview: "体験を共有するにはログインしてください。",
    reviewPlaceholder: "体験を共有...",
    submitting: "送信中...",
    submitReview: "レビューを送信",
    backToHotels: "ホテルに戻る",
    night: "泊",
    aboutTheHotel: "ホテルについて",
    featuredAmenities: "注目のアメニティ",
    allAmenities: "すべてのアメニティ",
    bestPriceGuaranteed: "最安値保証",
    bookYourStay: "宿泊を予約",
    checkAvailability: "空室を確認",
    freeCancellationHotel: "チェックイン48時間前まで無料キャンセル",
    backToPackages: "パッケージに戻る",
    packageDescription: "パッケージ説明",
    bestValue: "ベストバリュー",
    perPackage: "合計",
    selectDepartureDate: "出発日を選択",
    bookPackageNow: "このパッケージを予約",
    customizeItinerary: "旅程をカスタマイズ",
    priceIncludesTax: "価格には全ての税金が含まれています",
    insuranceIncluded: "旅行保険付き",
    destinationNotFound: "目的地が見つかりません",
    destinationNotFoundDesc: "お探しの目的地は存在しません。",
    errorInvalidCredentials: "メールアドレスまたはパスワードが正しくありません。",
    errorEmailNotConfirmed: "メールアドレスを確認してください。",
    errorRateLimit: "試行回数が多すぎます。後でもう一度お試しください。",
    errorUnexpected: "予期しないエラーが発生しました。",
    checkEmailConfirm: "アカウントを確認するためにメールをチェックしてください。",
  },
  vi: {
    home: "Trang chủ",
    destinations: "Điểm đến",
    hotels: "Khách sạn",
    packages: "Gói tour",
    contact: "Liên hệ",
    bookNow: "Đặt ngay",
    searchPlaceholder: "Bạn muốn đi đâu?",
    heroTitle: "Du lịch Red Velvet cao cấp",
    heroSubtitle: "Trải nghiệm sự xa hoa chưa từng có với các hướng dẫn du lịch được tuyển chọn của chúng tôi.",
    viewDetails: "Xem chi tiết",
    exploreMore: "Khám phá thêm",
    contactAgent: "Liên hệ đại lý",
    login: "Đăng nhập",
    signup: "Đăng ký",
    profile: "Hồ sơ",
    logout: "Đăng xuất",
    featuredDestinations: "Điểm đến nổi bật",
    popularCategories: "Danh mục phổ biến",
    luxuryStays: "Kỳ nghỉ sang trọng",
    luxuryStaysDesc: "Bộ sưu tập các khách sạn và resort danh tiếng nhất thế giới.",
    curatedTourPackages: "Gói tour được tuyển chọn",
    curatedTourPackagesDesc: "Lịch trình được thiết kế kết hợp tinh hoa của sang trọng, phiêu lưu và văn hóa.",
    exclusiveOffers: "Ưu đãi độc quyền",
    bookStay: "Đặt phòng",
    perNight: "mỗi đêm",
    recommended: "Được đề xuất",
    allInclusive: "Trọn gói",
    experienceIndia: "Trải nghiệm Ấn Độ",
    experiencePackages: "Gói trải nghiệm",
    experiencePackagesDesc: "Trải nghiệm du lịch được tuyển chọn cho mọi loại du khách",
    exploreWorld: "Khám phá thế giới",
    popularDestinations: "Điểm đến phổ biến",
    popularDestinationsDesc: "Khám phá những điểm đến ngoạn mục nhất thế giới",
    viewAll: "Xem tất cả",
    footerDesc: "Nền tảng du lịch cao cấp đầu tiên trên thế giới được thiết kế cho những người thích phiêu lưu hiện đại. Sang trọng, đơn giản hóa.",
    privacyPolicy: "Chính sách bảo mật",
    termsOfService: "Điều khoản dịch vụ",
    allRightsReserved: "Bảo lưu mọi quyền.",
    heritageAndCulture: "Di sản & Văn hóa",
    heritageAndCultureDesc: "Đền chùa và di tích cổ",
    adventureAndThrills: "Phiêu lưu & Mạo hiểm",
    adventureAndThrillsDesc: "Leo núi và thể thao mạo hiểm",
    wildlifeSafari: "Safari động vật hoang dã",
    wildlifeSafariDesc: "Vườn quốc gia và khu bảo tồn",
    beachAndRelaxation: "Biển & Thư giãn",
    beachAndRelaxationDesc: "Kỳ nghỉ ven biển",
    spiritualJourneys: "Hành trình tâm linh",
    spiritualJourneysDesc: "Hành hương và sức khỏe",
    foodAndCulinary: "Ẩm thực & Nấu ăn",
    foodAndCulinaryDesc: "Trải nghiệm ẩm thực địa phương",
    wifi: "Wifi",
    breakfast: "Bữa sáng",
    pool: "Hồ bơi",
    dining: "Nhà hàng",
    speakWithSpecialist: "Nói chuyện with chuyên gia",
    speakWithSpecialistDesc: "Các đại lý du lịch cao cấp của chúng tôi sẵn sàng tạo nên kỳ nghỉ hoàn hảo cho bạn.",
    emailUs: "Email cho chúng tôi",
    callAnytime: "Gọi bất cứ lúc nào",
    fullName: "Họ và tên",
    emailAddress: "Địa chỉ email",
    yourInquiry: "Yêu cầu của bạn",
    inquiryPlaceholder: "Hãy cho chúng tôi biết về điểm đến mơ ước của bạn...",
    sendInquiry: "Gửi yêu cầu",
    sending: "Đang gửi...",
    messageReceived: "Đã nhận tin nhắn",
    messageReceivedDesc: "Chuyên gia của chúng tôi sẽ liên hệ with bạn sớm.",
    sendAnotherMessage: "Gửi tin nhắn khác",
    confirmBooking: "Xác nhận đặt chỗ",
    travelDates: "Ngày đi",
    numberOfTravelers: "Số lượng du khách",
    paymentDetails: "Chi tiết thanh toán",
    cardholderName: "Tên chủ thẻ",
    cardNumber: "Số thẻ",
    processing: "Đang xử lý...",
    completeBooking: "Hoàn tất đặt chỗ",
    baseFare: "Giá cơ bản",
    taxesFees: "Thuế & Phí",
    total: "Tổng cộng",
    secureCheckout: "Thanh toán an toàn",
    welcome: "Chào mừng",
    accountSettings: "Cài đặt tài khoản",
    memberBenefits: "Quyền lợi thành viên",
    premiumStatus: "Trạng thái Premium",
    exclusiveOffersAvailable: "Có ưu đãi độc quyền",
    travelCreditAvailable: "Có tín dụng du lịch",
    planNextTrip: "Lên kế hoạch chuyến đi tiếp theo",
    planNextTripDesc: "Khám phá các điểm đến mới cho mùa đông 2024.",
    myBookings: "Đặt chỗ của tôi",
    newBooking: "Đặt chỗ mới",
    viewDetailsBtn: "Xem chi tiết",
    noBookingsYet: "Bạn chưa đặt chuyến đi nào.",
    bookFirstTrip: "Đặt chuyến đi đầu tiên",
    aboutJourney: "Về chuyến đi này",
    journeyHighlights: "Điểm nổi bật của hành trình",
    whatsIncluded: "Bao gồm những gì",
    premiumPackage: "Gói Premium",
    selectDate: "Chọn ngày",
    travelers: "Du khách",
    basePrice: "Giá gốc",
    serviceFee: "Phí dịch vụ",
    bookTripNow: "Đặt chuyến đi ngay",
    freeCancellation: "Hủy miễn phí đến 48 giờ trước chuyến đi.",
    backToDestinations: "Quay lại điểm đến",
    welcomeBack: "Chào mừng trở lại",
    enterCredentials: "Nhập thông tin đăng nhập để truy cập các chuyến du lịch sang trọng",
    email: "Email",
    password: "Mật khẩu",
    forgotPassword: "Quên mật khẩu?",
    signIn: "Đăng nhập",
    signingIn: "Đang đăng nhập...",
    noAccount: "Chưa có tài khoản?",
    createAccount: "Tạo tài khoản",
    joinUs: "Tham gia Orchids Travel để có trải nghiệm du lịch sang trọng độc quyền",
    creatingAccount: "Đang tạo tài khoản...",
    alreadyHaveAccount: "Đã có tài khoản?",
    flights: "Chuyến bay",
    flightsDesc: "Ưu đãi tốt nhất cho các chuyến bay quốc tế và nội địa.",
    tours: "Tour du lịch",
    toursDesc: "Gói nghỉ dưỡng trọn gói cho gia đình.",
    readyForAdventure: "Sẵn sàng cho cuộc phiêu lưu tiếp theo?",
    readyForAdventureDesc: "Tham gia cùng hàng ngàn du khách đã tìm thấy kỳ nghỉ mơ ước with Orchids Travel.",
    exploreFooter: "Khám phá",
    contactFooter: "Liên hệ",
    addDates: "Thêm ngày",
    search: "Tìm kiếm",
    noDestinationsFound: "Không tìm thấy điểm đến",
    noDestinationsFoundDesc: "Hãy thử điều chỉnh tìm kiếm hoặc bộ lọc của bạn.",
    clearAllFilters: "Xóa tất cả bộ lọc",
    startingFrom: "Bắt đầu từ",
    all: "Tất cả",
    romantic: "Lãng mạn",
    adventure: "Phiêu lưu",
    cultural: "Văn hóa",
    tropical: "Nhiệt đới",
    luxury: "Sang trọng",
    viewAllPackages: "Xem tất cả gói tour",
    viewAllHotels: "Xem tất cả khách sạn",
    guestReviews: "Đánh giá của khách",
    reviewsCount: "đánh giá",
    noReviewsYet: "Chưa có đánh giá. Hãy là người đầu tiên!",
    writeAReview: "Viết đánh giá",
    loginToReview: "Vui lòng đăng nhập để chia sẻ trải nghiệm.",
    reviewPlaceholder: "Chia sẻ trải nghiệm của bạn...",
    submitting: "Đang gửi...",
    submitReview: "Gửi đánh giá",
    backToHotels: "Quay lại khách sạn",
    night: "đêm",
    aboutTheHotel: "Về khách sạn",
    featuredAmenities: "Tiện nghi nổi bật",
    allAmenities: "Tất cả tiện nghi",
    bestPriceGuaranteed: "Đảm bảo giá tốt nhất",
    bookYourStay: "Đặt phòng của bạn",
    checkAvailability: "Kiểm tra phòng trống",
    freeCancellationHotel: "Hủy miễn phí đến 48 giờ trước khi nhận phòng",
    backToPackages: "Quay lại gói tour",
    packageDescription: "Mô tả gói tour",
    bestValue: "Giá trị tốt nhất",
    perPackage: "tổng",
    selectDepartureDate: "Chọn ngày khởi hành",
    bookPackageNow: "Đặt gói này",
    customizeItinerary: "Tùy chỉnh lịch trình",
    priceIncludesTax: "Giá đã bao gồm tất cả thuế",
    insuranceIncluded: "Bao gồm bảo hiểm du lịch",
    destinationNotFound: "Không tìm thấy điểm đến",
    destinationNotFoundDesc: "Điểm đến bạn tìm kiếm không tồn tại.",
    errorInvalidCredentials: "Email hoặc mật khẩu không hợp lệ.",
    errorEmailNotConfirmed: "Vui lòng xác nhận địa chỉ email của bạn.",
    errorRateLimit: "Quá nhiều lần thử. Vui lòng thử lại sau.",
    errorUnexpected: "Đã xảy ra lỗi không mong muốn.",
    checkEmailConfirm: "Vui lòng kiểm tra email của bạn để xác nhận tài khoản.",
  },
  ru: {
    home: "Главная",
    destinations: "Направления",
    hotels: "Отели",
    packages: "Пакеты",
    contact: "Контакты",
    bookNow: "Забронировать",
    searchPlaceholder: "Куда вы хотите поехать?",
    heroTitle: "Премиум Red Velvet Travel",
    heroSubtitle: "Испытайте роскошь как никогда раньше с нашими тщательно подобранными путеводителями.",
    viewDetails: "Подробнее",
    exploreMore: "Узнать больше",
    contactAgent: "Связаться с агентом",
    login: "Войти",
    signup: "Регистрация",
    profile: "Профиль",
    logout: "Выйти",
    featuredDestinations: "Избранные направления",
    popularCategories: "Популярные категории",
    luxuryStays: "Роскошное проживание",
    luxuryStaysDesc: "Коллекция самых престижных отелей и курортов мира.",
    curatedTourPackages: "Подобранные турпакеты",
    curatedTourPackagesDesc: "Маршруты ручной работы, сочетающие лучшее из роскоши, приключений и культуры.",
    exclusiveOffers: "Эксклюзивные предложения",
    bookStay: "Забронировать проживание",
    perNight: "за ночь",
    recommended: "Рекомендовано",
    allInclusive: "Всё включено",
    experienceIndia: "Откройте Индию",
    experiencePackages: "Пакеты впечатлений",
    experiencePackagesDesc: "Тщательно подобранные путешествия для каждого типа путешественника",
    exploreWorld: "Исследуйте мир",
    popularDestinations: "Популярные направления",
    popularDestinationsDesc: "Откройте самые захватывающие направления мира",
    viewAll: "Смотреть все",
    footerDesc: "Первая в мире премиальная туристическая платформа для современных искателей приключений. Роскошь, упрощённая.",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Условия использования",
    allRightsReserved: "Все права защищены.",
    heritageAndCulture: "Наследие и культура",
    heritageAndCultureDesc: "Древние храмы и памятники",
    adventureAndThrills: "Приключения и острые ощущения",
    adventureAndThrillsDesc: "Треккинг и экстремальный спорт",
    wildlifeSafari: "Сафари с дикими животными",
    wildlifeSafariDesc: "Национальные парки и заповедники",
    beachAndRelaxation: "Пляж и отдых",
    beachAndRelaxationDesc: "Отдых на побережье",
    spiritualJourneys: "Духовные путешествия",
    spiritualJourneysDesc: "Паломничество и оздоровление",
    foodAndCulinary: "Еда и кулинария",
    foodAndCulinaryDesc: "Местные гастрономические впечатления",
    wifi: "Wi-Fi",
    breakfast: "Завтрак",
    pool: "Бассейн",
    dining: "Ресторан",
    speakWithSpecialist: "Поговорите со специалистом",
    speakWithSpecialistDesc: "Наши агенты по элитному туризму готовы создать ваш идеальный отдых.",
    emailUs: "Напишите нам",
    callAnytime: "Позвоните",
    fullName: "Полное имя",
    emailAddress: "Электронная почта",
    yourInquiry: "Ваш запрос",
    inquiryPlaceholder: "Расскажите о вашем идеальном направлении...",
    sendInquiry: "Отправить запрос",
    sending: "Отправка...",
    messageReceived: "Сообщение получено",
    messageReceivedDesc: "Наш специалист свяжется с вами в ближайшее время.",
    sendAnotherMessage: "Отправить ещё сообщение",
    confirmBooking: "Подтвердите бронирование",
    travelDates: "Даты поездки",
    numberOfTravelers: "Количество путешественников",
    paymentDetails: "Данные оплаты",
    cardholderName: "Имя владельца карты",
    cardNumber: "Номер карты",
    processing: "Обработка...",
    completeBooking: "Завершить бронирование",
    baseFare: "Базовый тариф",
    taxesFees: "Налоги и сборы",
    total: "Итого",
    secureCheckout: "Безопасная оплата",
    welcome: "Добро пожаловать",
    accountSettings: "Настройки аккаунта",
    memberBenefits: "Преимущества участника",
    premiumStatus: "Премиум статус",
    exclusiveOffersAvailable: "Доступны эксклюзивные предложения",
    travelCreditAvailable: "Доступен кредит на путешествия",
    planNextTrip: "Спланируйте следующую поездку",
    planNextTripDesc: "Откройте наши новые направления на зиму 2024.",
    myBookings: "Мои бронирования",
    newBooking: "Новое бронирование",
    viewDetailsBtn: "Подробнее",
    noBookingsYet: "У вас пока нет забронированных поездок.",
    bookFirstTrip: "Забронируйте первую поездку",
    aboutJourney: "Об этом путешествии",
    journeyHighlights: "Основные моменты путешествия",
    whatsIncluded: "Что включено",
    premiumPackage: "Премиум пакет",
    selectDate: "Выберите дату",
    travelers: "Путешественники",
    basePrice: "Базовая цена",
    serviceFee: "Сервисный сбор",
    bookTripNow: "Забронировать поездку сейчас",
    freeCancellation: "Бесплатная отмена за 48 часов до поездки.",
    backToDestinations: "Назад к направлениям",
    welcomeBack: "С возвращением",
    enterCredentials: "Введите данные для доступа к вашим люксовым путешествиям",
    email: "Email",
    password: "Пароль",
    forgotPassword: "Забыли пароль?",
    signIn: "Войти",
    signingIn: "Вход...",
    noAccount: "Нет аккаунта?",
    createAccount: "Создать аккаунт",
    joinUs: "Присоединяйтесь к Orchids Travel для эксклюзивного люксового отдыха",
    creatingAccount: "Создание аккаунта...",
    alreadyHaveAccount: "Уже есть аккаунт?",
    flights: "Авиабилеты",
    flightsDesc: "Лучшие предложения на международные и внутренние рейсы.",
    tours: "Туры",
    toursDesc: "Пакеты «всё включено» для семейного отдыха.",
    readyForAdventure: "Готовы к следующему приключению?",
    readyForAdventureDesc: "Присоединяйтесь к тысячам путешественников, нашедших отпуск мечты с Orchids Travel.",
    exploreFooter: "Исследовать",
    contactFooter: "Контакты",
    addDates: "Добавить даты",
    search: "Поиск",
    noDestinationsFound: "Направления не найдены",
    noDestinationsFoundDesc: "Попробуйте изменить поиск или фильтры.",
    clearAllFilters: "Сбросить все фильтры",
    startingFrom: "От",
    all: "Все",
    romantic: "Романтика",
    adventure: "Приключения",
    cultural: "Культура",
    tropical: "Тропики",
    luxury: "Люкс",
    viewAllPackages: "Все пакеты",
    viewAllHotels: "Все отели",
    guestReviews: "Отзывы гостей",
    reviewsCount: "отзывов",
    noReviewsYet: "Пока нет отзывов. Будьте первым!",
    writeAReview: "Написать отзыв",
    loginToReview: "Войдите, чтобы поделиться опытом.",
    reviewPlaceholder: "Поделитесь впечатлениями...",
    submitting: "Отправка...",
    submitReview: "Отправить отзыв",
    backToHotels: "Назад к отелям",
    night: "ночь",
    aboutTheHotel: "Об отеле",
    featuredAmenities: "Основные удобства",
    allAmenities: "Все удобства",
    bestPriceGuaranteed: "Гарантия лучшей цены",
    bookYourStay: "Забронировать проживание",
    checkAvailability: "Проверить наличие",
    freeCancellationHotel: "Бесплатная отмена за 48ч до заезда",
    backToPackages: "Назад к пакетам",
    packageDescription: "Описание пакета",
    bestValue: "Лучшая цена",
    perPackage: "всего",
    selectDepartureDate: "Выберите дату отправления",
    bookPackageNow: "Забронировать этот пакет",
    customizeItinerary: "Настроить маршрут",
    priceIncludesTax: "Цена включает все налоги",
    insuranceIncluded: "Страховка включена",
    destinationNotFound: "Направление не найдено",
    destinationNotFoundDesc: "Направление, которое вы ищете, не существует.",
    errorInvalidCredentials: "Неверный email или пароль.",
    errorEmailNotConfirmed: "Пожалуйста, подтвердите ваш адрес электронной почты.",
    errorRateLimit: "Слишком много попыток. Пожалуйста, попробуйте позже.",
    errorUnexpected: "Произошла непредвиденная ошибка.",
    checkEmailConfirm: "Пожалуйста, проверьте свою электронную почту, чтобы подтвердить свою учетную запись.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
